### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [gpac/mp4box.js#103]
what is this error? mp4box.all.js:38 [0:00:45.536] [BoxParser] Parsing of box mehd read 4 more bytes than the indicated box data size, seeking backwards. 

Why no warning?

**Comment by cconcolato** [comment]
could be a warning indeed but in general it means either the file is invalid or there is bug in mp4box.js. Given that the issue is very old, it's probably fixed already. Reopen if this is not the case.
