### ISSUE TITLE
Question about frame structure

### ISSUE THREAD

**Issue by publicocean0** [gpac/mp4box.js#105]
I have a new idea But i d like ask you a opinion you are more espert in video file format.
As you told in a previous post you keep a map of frames. So you can identify every frame. 
I dont exactly But i suppose inside frame there is byteaaray encoded in a specific codec.
It is possibile for you to convert this frame in a frame of another format ? For example webm?

**Comment by cconcolato** [comment]
Converting frames (encoding changes) is out of scope for mp4box.js. mp4box.js provides the frame content for whatever need you have.
