### ISSUE TITLE
Question about encryption (CENC)

### ISSUE THREAD

**Issue by osmestad** [gpac/mp4box.js#106]
Does this (or could it) support encrypted content?
(Seems to fail when I try.)

What I am looking for is a way to play back content encrypted with CENC using ClearKey in browsers that do not support ClearKey in their EME (Encrypted Media Extensions) implementations  (Safari and IE seem to lack this). 

I assume an approach like this that parses the MP4 data will be required and then do the decryption before passing the data to the MSE level (or maybe it would be possible to polyfill the EME API somehow).

**Comment by osmestad** [comment]
Some more details on what I am trying to do:
I encrypt an MP4 AAC audio file with:
MP4Box -crypt crypt.xml file.m4a -out file_enc.m4a
Then I would like to play that back in browser. I looked a bit at the callbacks available (onSegment and onSamples), but I think this would require implementation inside mp4box.js?
The file in question has this mime type:
	audio/mp4; codecs="enca"; profiles="mp42,dby1,isom,M4A "
I assume the "pssh" box would need to be parsed for the key info, but I am a bit unsure where would be the correct location to hook in the actual decryption, I guess it would need to access any "mdat" boxes?

**Comment by veacks** [comment]
Hi @osmestad 
Did you find any work around for that?

**Comment by U-siro** [comment]
https://stackoverflow.com/questions/33632240/how-to-encrypt-webm-or-mp4-file-using-clearkey-and-then-play-it
I want to do it using node.

**Comment by tbranyen** [comment]
I know this issue is fairly old, but I've started on a PR to add pssh box writing: #174 this should allow mp4box to support facilitating DRM, but defer completely to a CDM to decrypt. This simply gets the data in the right places for encryption implementation details to trigger.
