### ISSUE TITLE
Corruption after seeking.

### ISSUE THREAD

**Issue by kuwerty** [gpac/mp4box.js#107]
I'm seeing corruption after seeking.

If you seek (I'm guessing to a non keyframe) then both Firefox and Safari show corruption until the next keyframe comes along.

Although I found this in my own code I'm able to reproduce it using the demo player (http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/) and the Bad Influence movie on Firefox and Safari on OSX.  FYI: for whatever reason Firefox doesn't always let you seek but reload a few times and it seems to enable the seekbar.

I found this bug 'https://github.com/gpac/mp4box.js/issues/64' and this commit 'https://github.com/gpac/mp4box.js/commit/ff816c5682996ab48dd24e442f9a9329cc422e88' that seem like they might have addressed something similar but the latest code sets trun sample_flags to 0.  Tried migrating the change to the latest code but no video shows up so I suspect there's more to it.

Any idea on a suitable workaround?

**Comment by cconcolato** [comment]
I've tried in latest Firefox, Safari and Chrome and seeking seems to work without corruption. But I tested your change (setting the sample flags) also works (FF, Chrome) and is more correct. I applied your patch in https://github.com/gpac/mp4box.js/commit/bf6bf6d65f6eec7fcae1fb6550e2206917556d3a. Thanks.
