### ISSUE TITLE
Mp4Box.js Unable to get rebuild video track from a file

### ISSUE THREAD

**Issue by TechTotie** [gpac/mp4box.js#111]
Hi All,

 I am new to MP4Box.js and also to JS. 
 I was trying to use MP4Bos.js and get information about tracks and also separate tracks and rebuild them from segments using MediaSource Extension. 
However I am unable to do it, all at once, but on case to case basis yes. 
I am able to rebuild audio and video track separately and play them separately. 
I am only facing issue when I try to rebuidling/reconstructing audio and video at same time(I mean on a single onReady Callback ), but text tracks is working fine in all cases. 

The application is present in https://github.com/TechTotie/mp4boxAppln, as I could not attach files, so had to check it in in Git and provide link here
 (could not share the mp4 file though). I hosted the app on a local server and then used it , else cannot use it directly using file:///.  

One more doubt is that, Is it necessary that all processing should be done in onReady callback itself, if done at any other time after getting onReady callback, it did not work.

Please let me know how to use MP4Box correctly.

Thanks and Regards,
TechTotie.

**Comment by cconcolato** [comment]
Closing the issue as it is very old and maybe is fixed by now. Reopen if you still have the problem.
