### ISSUE TITLE
can you show an example how to segment media file and play it in browser?

### ISSUE THREAD

**Issue by peter--barnes** [gpac/mp4box.js#113]
the examples are not easy to be understand,I tried to use  source code in the "test" folder , but it seems doesn't work.

 Then I tried to write code as "README.md" show. Now ,the array buffer contain MP4 data seems been segmented (I can see a lot of log in browser).
**But when I tried to append them to source buffer , the browser tell me it can't be decoded. Is there any example can show how to append and play the segmented buffer?**
(I also tried to simulate the "test/index.js : mp4box.onSegment()" , but "sb.pendingAppends.push(xxx)" seems  to be invalid, sourceBuffer doesn't have this function).

Below is my source code,the code use unsegmented MP4 file,the file it self is ok and the mimeCodec also the right one.The file can also be segmented  by C/C++ MP4BOX (then browser can also play it correctly)
the code is simulated from "mozilla MDN":
https://github.com/nickdesaulniers/netfix/blob/gh-pages/demo/bufferAll.html
https://developer.mozilla.org/en-US/docs/Web/API/MediaSource

```

 var video = document.getElementById('test_video0');
var assetURL = 'video/carmer_101.mp4';
var mimeCodec = 'video/mp4; codecs="avc1.4d0020"';
if ('MediaSource' in window && MediaSource.isTypeSupported(mimeCodec)) {
    var mediaSource = new MediaSource;
    //create an URL (from mediaSource OBJ) as video's source
    video.src = URL.createObjectURL(mediaSource);
    //listen source's open
    mediaSource.addEventListener('sourceopen', on_source_open);
} else {
    console.error('Unsupported MIME type or codec: ', mimeCodec);
}
function on_source_open(_) {
    var mediaSource = this;
    var sourceBuffer = mediaSource.addSourceBuffer(mimeCodec);
    var xhr = new XMLHttpRequest;
    xhr.open('get', assetURL);
    xhr.responseType = 'arraybuffer';
    xhr.onload = function () {

        console.log("on response"); 
        sourceBuffer.addEventListener('updateend', function (_) {
                mediaSource.endOfStream();
                video.play();
        });
        var mp4box = new MP4Box();

        mp4box.onMoovStart = function () {
            console.log("Starting to receive File Information");
        }
        mp4box.onReady = function(info) {
            console.log(info.mime);
            mp4box.onSegment = function (id, user, buffer, sampleNum) {
                console.log("Received segment on track "+id+" for object "+user+" with a length of "+buffer.byteLength+",sampleNum="+sampleNum);
                user.appendBuffer(buffer);
            };
            var options = { nbSamples: 100 };
            mp4box.setSegmentOptions(info.tracks[0].id, sourceBuffer, options);  
            var initSegs = mp4box.initializeSegmentation();  
            mp4box.start();
        };

        var ab = xhr.response;
        ab.fileStart = 0;
        var nextBufferStart = mp4box.appendBuffer(ab);
        mp4box.flush();
    };
    xhr.send();
};



```

**Comment by mmorainville** [comment]
Hi,

I would also like to know, because I'm trying to do the exact same thing but without success.
I have an unsegmented MP4 which plays fine while loaded directly but if I segment it with mp4box.js, the data is not loaded and the video does not play.
My code is very similar to peter--barnes' one. The difference is that I push the segments in an array to serve as a buffer and then I append them later in the sourceBuffer of the mediaSource.

```
var tmpBuffer = []
mp4box.onSegment = function (id, user, buffer) {
    console.log("Received segment on track "+id+" for object "+user+" with a length of "+buffer.byteLength);
    tmpBuffer .push(buffer);
}
```

`sourceBuffer.appendBuffer(tmpBuffer .shift());`

@peter--barnes: did you succeed in reading a segmented video since you opened this issue?

Regards,
Mathieu

**Comment by Andrews54757** [comment]
@peter--barnes @mmorainville 

I think I have a reason to why it does not work. MediaSource specifies that you append the "initialization" buffer before appending anything else. With mp4box, the initialization buffers are returned with the `mp4box.initializeSegmentation()` function. Append the results to sourcebuffer first.

**Comment by cconcolato** [comment]
This seems to have a solution. Reopen if you still have a problem.
