### ISSUE TITLE
Is it possible to convert WebRTC stream to DASH?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [gpac/mp4box.js#116]
YouTube allows to run real-time broadcasts. See https://youtube.com/my_live_events.

There are 2 ways to run real-time broadcasts: 1. using Google+ Hangouts API and 2. using RTMP/DASH.

But according to https://developers.google.com/+/hangouts/support-faq, Google will close Hangouts API for video app developments starting from April 25, 2017.

For developers, this means we will not be able to create our own custom applications using Hangouts API that stream video (including YouTube).

I need to stream video and audio from the browser (web app) directly to YouTube Live without any intermediate server (for converting WebRTC to DASH or RTMP). Is it possible?

Currently YouTube Live Streaming API supports only RTMP and DASH, not WebRTC: https://developers.google.com/youtube/v3/live/docs/liveStreams#cdn.ingestionType

Is it possible somehow to create (segment) DASH stream from WebRTC (e.g. using mp4box.js) on client-side in browser and stream it to YouTube endpoint? If yes, how?

According to https://developers.google.com/youtube/v3/live/guides/encoding-with-dash, YouTube Live DASH endpoint supports H.264 and AAC codecs in ISO BMFF (MP4) container and VP8/VP9 and Vorbis/Opus codecs in WebM container. All these codecs currently are native for WebRTC and browsers and do not requires transcoding on intermediate server.

**Comment by cconcolato** [comment]
See #230 or #185
