### ISSUE TITLE
mp4 remux problem

### ISSUE THREAD

**Issue by JimmyVV** [gpac/mp4box.js#127]
Hi.  i feel much confused, because i couldn't play a mp4 file which i made it by meself. i want to ask u for a help. 

when i remux a buffer to a mp4 file, i create trak and mdat boxes. but I couldn't play it, i don't know why. 

I just separate video and audio into different trak. and when i remux them into mdat, i just push the audio buffer in front of video buffer, not mix them like one audio, one video, one audio .... 

so, it is only one way that we need to mix audio and video into one mdat, like audio + video + audio .... then we could normally play a mp4 file?

**Comment by cconcolato** [comment]
It is not clear if this issue is related to mp4box.js. Closing. If you still have a problem, reopen providing more details and an example file.
