### ISSUE TITLE
mehd box parsed incorrectly

### ISSUE THREAD

**Issue by ntrrgc** [gpac/mp4box.js#129]
Actual contents of the box:

```
dd bs=1 status=none if=fragmented.mp4 skip=$((28+58+8+108+21+8)) count=16 |hexdump -C
00000000  00 00 00 10 6d 65 68 64  00 00 00 00 00 00 00 00  |....mehd........|
00000010
```

Box decoded by the file analyzer:

![](http://i.imgur.com/QlsycjJ.png)

I don't know if having a fragment_duration of zero in a `mehd` box is legal in ISO BMFF, but definitively it should not be decoded as "version=1, fragment_duration=32".

**Comment by rbouqueau** [comment]
Could you share the file please?

**Comment by ntrrgc** [comment]
[sintel_trailer-720p-fragmented.mp4.zip](https://github.com/gpac/mp4box.js/files/1248763/sintel_trailer-720p-fragmented.mp4.zip)

**Comment by rbouqueau** [comment]
I could reproduce, thank you.

**Comment by rbouqueau** [comment]
@cconcolato I'd be interested to be able to setup a file analyzer here. If I launch it from the test directory, it doesn't execute correct. Is there a procedure?

**Comment by cconcolato** [comment]
That should be fixed with d5b3d8572e4adbd7f1f08d432977a31dfe170040, it was a stupid typo.

@rbouqueau you have to run it through a web server

**Comment by rbouqueau** [comment]
@cconcolato I tried but the filereader rendering is not ok. So I assumed there was another manip!

**Comment by cconcolato** [comment]
If it's an issue with rendering, maybe it's missing a JS library. I don't think they are installed by default.

**Comment by cconcolato** [comment]
Seems like the initial issue was fixed.
