### ISSUE TITLE
Question about combining audio and video tracks

### ISSUE THREAD

**Issue by MindofGhost** [gpac/mp4box.js#130]
Hi! I need to combine audio and video tracks from two different files into one file. I mean that I have two mp4 containers, the first with one audio track and the second with one video track. Can I do this with mp4box.js? If so, how? If not, do you plan to add the "-add" and "-rem" functions?

**Comment by MindofGhost** [comment]
I mean that I have two mp4 containers, the first with one audio track and the second with one video track

**Comment by tbranyen** [comment]
This currently works with mp4box. Simply create two different boxes and append their track user objects (source buffers) into the same media source.

**Comment by desean1625** [comment]
@tbranyen I stumbled across this and have attempted to figure it out but seem unable to get it correct. It appears that I create the boxes init the segments and append the buffers, but what happens is the second file is put at timestamp 0 and not at the end of the first mp4

https://codesandbox.io/s/romantic-hodgkin-9kfcm?file=/src/App.js

**Comment by cconcolato** [comment]
@desean1625 The HTML/MSE spec dictates how it would work. If you start appending data that has the same timestamp it overwrites the existing data.

Closing this issue as it seems that it does not need changes in MP4Box.js.
