### ISSUE TITLE
How to use with streaming link with embedded subtitles?

### ISSUE THREAD

**Issue by mauriciogior** [gpac/mp4box.js#131]
I'm trying to play a stream (mkv)  that has embedded subtitles in my browser.
I can successfully play using the default video api, but I'm not finding any example or source code on how to use mp4box with my video tag.

How do I initialize my video with the library? For example, with videojs I just need to call it passing the `id` as reference (`videojs('my-player')`).

Thanks.

**Comment by rbouqueau** [comment]
As you may have noticed, mp4box.js can only demux mp4, not mkv. What's your plan on using mp4box.js?

**Comment by mauriciogior** [comment]
I'm basically streaming from magnet links a MKV video. I figured it might work with mp4box.js.
Let's say it's a streaming of mp4 with embedded subtitles, how do I load it and play the video?

Thanks.

**Comment by rbouqueau** [comment]
There is a player application demo: http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/
Code: https://github.com/gpac/mp4box.js/tree/master/test

Have you tried it already?

**Comment by mauriciogior** [comment]
Yes, it's great, but I don't know where to start looking at...

**Comment by cconcolato** [comment]
mp4box.js cannot handle MKV files.
