### ISSUE TITLE
Tests fail to run on Node 8 (and 7)

### ISSUE THREAD

**Issue by bbcrddave** [gpac/mp4box.js#132]
The tests will not run on new versions of Node for the reason laid out in https://github.com/karma-runner/grunt-karma/issues/212.

Upgrading the required versions of karma and grunt-karma as described at https://github.com/karma-runner/grunt-karma/issues/212#issuecomment-313376197 fixes this issue.

**Comment by rbouqueau** [comment]
Thanks for reporting. Ok here with the patch (node 8.5.0). Could you check on your side and close if ok?

**Comment by bbcrddave** [comment]
All tasks run successfully on node 8.2.0 with above patch :+1:
