### ISSUE TITLE
Filereader.html in test/ links to missing files in lib/

### ISSUE THREAD

**Issue by davemevans** [gpac/mp4box.js#133]
The page in the test folder for testing interactively links to jquery code and css in lib/ (see below), but these files don't exist when the repo is cloned.

Most of them can be grabbed from cdnjs, but the slider plugin looks like it came from https://gist.github.com/pjezek/45fb7c699af507de1d9a.

Please update the test page, or provide the relevant libraries to run the test application.

```
<!-- Include basic JQuery and JQuery UI files -->
<script src="lib/jquery/jquery.js"></script>
<link href="lib/jquery-ui/jquery-ui.min.css" rel="stylesheet" type="text/css">
<script src="lib/jquery-ui/jquery-ui.min.js"></script>
<script src="lib/jquery-ui/jquery-ui.slider.custom.js"></script>

<!-- Include JQuery-based Fancytree skin, library, and extensions -->
<link href="lib/fancytree/ui.fancytree.min.css" rel="stylesheet" type="text/css">
<script src="lib/fancytree/jquery.fancytree-all.min.js" type="text/javascript"></script>

<script type="text/javascript" src="lib/d3/d3.js"></script>
```

**Comment by rbouqueau** [comment]
Thank you. I am not a js expert. Do you think it would be possible to make a pull request?

**Comment by bbcrddave** [comment]
You should be able simply to sync the contents of http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/lib/ to lib/

**Comment by gabrielmicko** [comment]
Why is it not included by default?

**Comment by gabrielmicko** [comment]
Until I am not getting answer for that I'll not open a PR, but here is how I fixed that on MaxOSX:

Install brew, if you haven't already:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
Install wget with brew if you havent't already:
`brew install wget --with-libressl`
Got to the lib folder:
`cd mp4box.js/test/lib`
Download the files:
`wget -r -np -nH --cut-dirs=3 -R index.html http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/lib/`

Now it works!

**Comment by bbcrddave** [comment]
> Why is it not included by default @bbcrddave ?

I don't know, it's not my project :smile:

My comment was simply implying that it would be easy enough for the project devs to fix by simply pulling down the files into the repo in the way you suggest in https://github.com/gpac/mp4box.js/issues/133#issuecomment-351962159

**Comment by gabrielmicko** [comment]
You're right, sorry. @cconcolato might be able to answer it.

**Comment by cconcolato** [comment]
Issue is fixed now.
