### ISSUE TITLE
mvhd duration

### ISSUE THREAD

**Issue by songguangyu** [gpac/mp4box.js#136]
initializeSegmentation will reset mvhd duration, it will make html5 video duration is 0.is it a bug or i use it wrong? thank you.

**Comment by songguangyu** [comment]
@cconcolato

**Comment by cconcolato** [comment]
mvhd indicates the duration of the non-fragmented part of the file. It should be zero when the file is fragmented. The duration is then reported in the mehd box.

**Comment by songguangyu** [comment]
just live need mvhd duration zero, vod need mvhd duration show in controls.

**Comment by songguangyu** [comment]
![image](https://user-images.githubusercontent.com/6869168/31419354-0c647a2c-ae01-11e7-8037-fd907f43201a.png)

In vod I should set isFragmentationInitialized is true?

**Comment by cconcolato** [comment]
Live or VoD does not matter. If it is fragmented, the total duration is the sum of mehd and mvhd, but the way mp4box.js works (as recommended in DASH or CMAF) the mvhd is 0.
