### ISSUE TITLE
Saving to a file

### ISSUE THREAD

**Issue by avatsaev** [gpac/mp4box.js#142]
Sorry this might be a stupid question:

I'm using mp4box.js on backend (nodejs), and I couldn't find a lot of examples, just the one from the README.

Basically what I'm doing is downloading mp4 chunks from a DASH live stream, and appending them progressively in the mp4box as array buffers, I'd like to know how do I save to a single MP4 file on the file system when i'm done.

Again, sorry for the stackoverflow type question.

**Comment by cconcolato** [comment]
It's a use case that is not covered at the moment. If the purpose is simply concatenating mp4 chunks, why use MP4Box.js?

**Comment by daominhsangvn** [comment]
I'm looking for this feature as some websites are using this technology to stream the video and i want to download those videos. Is that possible?
