### ISSUE TITLE
MP4 chunk, does not work?

### ISSUE THREAD

**Issue by BrunoGysin** [gpac/mp4box.js#143]
I need to make a player, and I think mp4box.js is the solution, but I think I'm doing something wrong.

I'm downloading the file in byte range: 0-4194303 (start-End)
and appendBuffer to mp4box:
```
buffer.fileStart = aStartOffset; // aStartOffset = 0
var nextStart = mp4box.appendBuffer(buffer);
console.log('nextStart: ', nextStart)
```

but nextStart returns:  3720962338
does not this return the next start byte to read?

the file is .mp4
I need to convert? for something specific?
or
do I need to add something specific at the beginning of the file?

is the first time with this.

**Comment by cconcolato** [comment]
mp4box.js returns appendBuffer returns the next useful position to parse. I'm not sure given that I don't have your file but I would assume that the file starts with the mdat box. mp4box.js needs the moov box to be able to process the file. So it wants to skip the parsing of the mdat and tells you to fetch the bytes after the mdat. Reopen this issue if needed.
