### ISSUE TITLE
Streaming over websockets to MSE

### ISSUE THREAD

**Issue by aaronovz1** [gpac/mp4box.js#151]
Hello, 

I am trying to live stream H.264 in an MP4 container over websockets to a browser client and play the video using MSE. I assumed I needed to use mp4box to ensure the segments that are passed to MSE are boxed correctly because if I try to use them as-is, MSE complains that it can't decode it. The problem is I never get the onReady event with the data I am passing to mp4box. The MP4 data is generated using libav/ffmpeg in a C++ application with movflags "frag_keyframe+omit_tfhd_offset+empty_moov+default_base_moof". I save the init segment on the server side and send it to the client when it connects.

The browser code is:
```
var mp4box = new MP4Box();

mp4box.onError = function(e) {
  console.log("mp4box failed to parse data.");
};

mp4box.onMoovStart = function () {
    console.log("Starting to receive File Information");
};

mp4box.onReady = function(info) {
    console.log(info.mime);
    mp4box.onSegment = function (id, user, buffer, sampleNum) {
        console.log("Received segment on track "+id+" for object "+user+" with a length of "+buffer.byteLength+",sampleNum="+sampleNum);
        user.appendBuffer(buffer);
    };

    var options = { nbSamples: 100 };
    mp4box.setSegmentOptions(info.tracks[0].id, sourceBuffer, options);
    var initSegs = mp4box.initializeSegmentation();
    mp4box.start();
};


websocket.addEventListener('message', function(e) {
    e.data.fileStart = 0;
    var nextBufferStart = mp4box.appendBuffer(e.data);
    mp4box.flush();

 }, false);
```

If I write the data I send over websocket into a file, it will play in VLC. The info from mp4info on that file:
```
File:
  major brand:      iso5
  minor version:    200
  compatible brand: iso6
  compatible brand: mp41
  fast start:       yes

Movie:
  duration:   0 ms
  time scale: 1000
  fragments:  yes

Found 1 Tracks
Track 1:
  flags:        3 ENABLED IN-MOVIE
  id:           1
  type:         Video
  duration: 0 ms
  language: und
  media:
    sample count: 0
    timescale:    22
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 29.806 Kbps
    sample count with fragments: 720
    duration with fragments:     720
    duration with fragments:     32727 (ms)
  display width:  320.000000
  display height: 240.000000
  Sample Description 0
    Coding:      avc1 (H.264)
    Width:       320
    Height:      240
    Depth:       24
    AVC Profile:          100 (High)
    AVC Profile Compat:   0
    AVC Level:            13
    AVC NALU Length Size: 4
    AVC SPS: [2764000dac2d90141fb0110000030001000003002c9da1c29920]
    AVC PPS: [28ee3cb0]
    Codecs String: avc1.64000D
```

**Comment by nullpilot** [comment]
I'm currently doing something smilar, and while I haven't gotten the whole thing working yet, setting the fileStart property to the actual byteOffset in the file has lead to getting the info at least:

Add the byteOffset to your websocket data, then try this:

```
websocket.addEventListener('message', function(e) {
    e.data.fileStart = e.data.byteOffset;
    var nextBufferStart = mp4box.appendBuffer(e.data);
    mp4box.flush();

 }, false);
```

If you have made any progress towards this since you posted the issue, and don't mind sharing, it would be a great resource for anyone trying to work with this lib!

**Comment by aaronovz1** [comment]
I gave up on this and found jmuxer instead (https://github.com/samirkumardas/jmuxer). I just it raw H.264 and it handles repackaging into a container for MSE.

**Comment by cconcolato** [comment]
I agree with @nullpilot. The problem was probably that you were overriding the offset to 0 every time you received a buffer. If the buffer was too small, mp4box.js would never detect the moov. I'm closing the issue since you solved your problem it seems.
