### ISSUE TITLE
avcC box SPS and PPS arrays are written as all zero

### ISSUE THREAD

**Issue by oije2333** [gpac/mp4box.js#154]
Running the following code, which appends a buffer consisting of an entire MP4 file then reconstructs and saves the result to a new file, the SPS and PPS arrays in the avcC box are written as all zero:

`var mp4box = MP4Box.createFile();`
`mp4box.onReady = function(info) { this.save('example.mp4'); };`
`var buf;`
`// get buf somehow`
`buf.fileStart = 0;`
`mp4box.appendBuffer(buf);`

If avcC box is present in the resulting output file, its SPS and PPS arrays will be all zero, even though the correct data is present in the mp4box object.

This is due to a bug in `BoxParser.avcCBox.prototype.write` in mp4box.all.js (the bug may exist in other places, as well, but haven't checked everywhere).

When the SPS and PPS arrays are written out, they are mistakenly referenced as `this.SPS[i]` and `this.PPS[i]`. To fix the bug, these references need to be changed to `this.SPS[i].nalu` and `this.PPS[i].nalu`.

**Comment by tbranyen** [comment]
Fixed in #172 thanks for figuring out what the regression was!
