### ISSUE TITLE
save() doesn't work in Firefox

### ISSUE THREAD

**Issue by oije2333** [gpac/mp4box.js#156]
The save() method doesn't work in Firefox. To make it work in Firefox requires appending the anchor element to the document body; something like this:

```
var url = window.URL.createObjectURL(blob);
var a = document.createElement('a');

// Required in Firefox:
document.body.appendChild(a);

a.setAttribute('href', url);
a.setAttribute('download', filename);

// Required in Firefox:
a.setAttribute('target', '_self');

a.click();
window.URL.revokeObjectURL(url);
```

**Comment by cconcolato** [comment]
Thanks for the report. I have added your code and verified that it works in Firefox and did not break in Chrome.
