### ISSUE TITLE
Error - Skipping unrecognized top-level box...

### ISSUE THREAD

**Issue by Ayms** [gpac/mp4box.js#16]
It's working better, the video starts playing well, but then...back to #10... after 1mn the sound continues playing but the image freezes

Please see:

![logmp4box](https://cloud.githubusercontent.com/assets/759202/4151808/6aa3ebf2-3449-11e4-8008-c3a5d3df5740.png)

I supposed the codecs are supported by Chrome (?? if not it would not play at all)

And my logs, you can see the begining of the segments being appended in utf8/hex formats, please let me know if you need yours (or if you suspect that it can be an issue in Peersm but as far as I can see everything looks normal):

db_query/db_connected 1686 ms 674 Thu Sep 04 2014 16:58:29 GMT+0200 (Paris, Madrid (heure d’été))
init_media video/mp4 Thu Sep 04 2014 16:58:29 GMT+0200 (Paris, Madrid (heure d’été))
start_t0 received 1409842735672 Thu Sep 04 2014 16:58:55 GMT+0200 (Paris, Madrid (heure d’été))
moov start Thu Sep 04 2014 16:58:56 GMT+0200 (Paris, Madrid (heure d’été))
992472 bps nbBlocs 84 stream window 84 - sending sendme stream received 456168 - Buffer Amount: 0 1409842739350 Thu Sep 04 2014 16:58:59 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18678 stream length 498 Thu Sep 04 2014 16:58:59 GMT+0200 (Paris, Madrid (heure d’été))
996256 bps nbBlocs 85 stream window 85 - sending sendme stream received 953670 - Buffer Amount: 0 1409842743332 Thu Sep 04 2014 16:59:03 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18660 stream length 498 Thu Sep 04 2014 16:59:03 GMT+0200 (Paris, Madrid (heure d’été))
997448 bps nbBlocs 85 stream window 85 - sending sendme stream received 1451670 - Buffer Amount: 0 1409842747316 Thu Sep 04 2014 16:59:07 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18655 stream length 498 Thu Sep 04 2014 16:59:07 GMT+0200 (Paris, Madrid (heure d’été))
997904 bps nbBlocs 85 stream window 85 - sending sendme stream received 1949670 - Buffer Amount: 0 1409842751303 Thu Sep 04 2014 16:59:11 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18654 stream length 498 Thu Sep 04 2014 16:59:11 GMT+0200 (Paris, Madrid (heure d’été))
998432 bps nbBlocs 85 stream window 85 - sending sendme stream received 2447670 - Buffer Amount: 0 1409842755285 Thu Sep 04 2014 16:59:15 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18652 stream length 498 Thu Sep 04 2014 16:59:15 GMT+0200 (Paris, Madrid (heure d’été))
999120 bps nbBlocs 85 stream window 85 - sending sendme stream received 2945670 - Buffer Amount: 0 1409842759259 Thu Sep 04 2014 16:59:19 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18649 stream length 498 Thu Sep 04 2014 16:59:19 GMT+0200 (Paris, Madrid (heure d’été))
999320 bps nbBlocs 85 stream window 85 - sending sendme stream received 3443670 - Buffer Amount: 0 1409842763241 Thu Sep 04 2014 16:59:23 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18648 stream length 498 Thu Sep 04 2014 16:59:23 GMT+0200 (Paris, Madrid (heure d’été))
999440 bps nbBlocs 85 stream window 85 - sending sendme stream received 3941670 - Buffer Amount: 0 1409842767224 Thu Sep 04 2014 16:59:27 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18648 stream length 498 Thu Sep 04 2014 16:59:27 GMT+0200 (Paris, Madrid (heure d’été))
play media mp4box ready Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
mp4box mime: video/mp4; codecs=" avc1.640029" Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
mp4box mime: video/mp4; codecs=" mp4a.40.2" Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
init length 2 Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
init segment track 1 1261 Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 1261 ftypisomisom�moovlmvhd����X Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 1261 000000146674797069736f6d0000000169736f6d000004d96d6f6f760000006c6d76686400000000d005eaa6d005eaa60000 Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
init segment track 2 1141 Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 1141 ftypisomisomamoovlmvhd����X Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 1141 000000146674797069736f6d0000000169736f6d000004616d6f6f760000006c6d76686400000000d005eaa6d005eaa60000 Thu Sep 04 2014 16:59:30 GMT+0200 (Paris, Madrid (heure d’été))
979816 bps nbBlocs 83 stream window 83 - sending sendme stream received 4440666 - Buffer Amount: 0 1409842771930 Thu Sep 04 2014 16:59:31 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18729 stream length 498 Thu Sep 04 2014 16:59:31 GMT+0200 (Paris, Madrid (heure d’été))
999376 bps nbBlocs 85 stream window 85 - sending sendme stream received 4937670 - Buffer Amount: 0 1409842775200 Thu Sep 04 2014 16:59:35 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18648 stream length 498 Thu Sep 04 2014 16:59:35 GMT+0200 (Paris, Madrid (heure d’été))
999520 bps nbBlocs 85 stream window 85 - sending sendme stream received 5435670 - Buffer Amount: 0 1409842779179 Thu Sep 04 2014 16:59:39 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18648 stream length 498 Thu Sep 04 2014 16:59:39 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 379606 dmoofmfhdCLtraftfhdtfdt$trunlo Thu Sep 04 2014 16:59:40 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379606 dmoofmfhdCLtraftfhdtfdt$trunlo Thu Sep 04 2014 16:59:40 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379606 000000646d6f6f66000000106d66686400000000000000430000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 16:59:41 GMT+0200 (Paris, Madrid (heure d’été))
996792 bps nbBlocs 85 stream window 85 - sending sendme stream received 5933670 - Buffer Amount: 0 1409842783295 Thu Sep 04 2014 16:59:43 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18658 stream length 498 Thu Sep 04 2014 16:59:43 GMT+0200 (Paris, Madrid (heure d’été))
999808 bps nbBlocs 85 stream window 85 - sending sendme stream received 6431670 - Buffer Amount: 0 1409842787136 Thu Sep 04 2014 16:59:47 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18647 stream length 498 Thu Sep 04 2014 16:59:47 GMT+0200 (Paris, Madrid (heure d’été))
999480 bps nbBlocs 85 stream window 85 - sending sendme stream received 6929670 - Buffer Amount: 0 1409842791139 Thu Sep 04 2014 16:59:51 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18648 stream length 498 Thu Sep 04 2014 16:59:51 GMT+0200 (Paris, Madrid (heure d’été))
999800 bps nbBlocs 85 stream window 85 - sending sendme stream received 7427670 - Buffer Amount: 0 1409842795106 Thu Sep 04 2014 16:59:55 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18647 stream length 498 Thu Sep 04 2014 16:59:55 GMT+0200 (Paris, Madrid (heure d’été))
999688 bps nbBlocs 85 stream window 85 - sending sendme stream received 7925670 - Buffer Amount: 0 1409842799098 Thu Sep 04 2014 16:59:59 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18647 stream length 498 Thu Sep 04 2014 16:59:59 GMT+0200 (Paris, Madrid (heure d’été))
999704 bps nbBlocs 85 stream window 85 - sending sendme stream received 8423670 - Buffer Amount: 0 1409842803082 Thu Sep 04 2014 17:00:03 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18647 stream length 498 Thu Sep 04 2014 17:00:03 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 1 4258256 dmoofmfhdLtraftfhdtfdt$trunl��� Thu Sep 04 2014 17:00:08 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 4258256 dmoofmfhdLtraftfhdtfdt$trunl��� Thu Sep 04 2014 17:00:12 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 4258256 000000646d6f6f66000000106d66686400000000000000000000004c74726166000000107466686400020000000000010000 Thu Sep 04 2014 17:00:16 GMT+0200 (Paris, Madrid (heure d’été))
870976 bps nbBlocs 74 stream window 74 - sending sendme stream received 8927148 - Buffer Amount: 0 1409842817669 Thu Sep 04 2014 17:00:17 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19236 stream length 498 Thu Sep 04 2014 17:00:17 GMT+0200 (Paris, Madrid (heure d’été))
888704 bps nbBlocs 76 stream window 76 - sending sendme stream received 9424152 - Buffer Amount: 549 1409842820508 Thu Sep 04 2014 17:00:20 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19143 stream length 498 Thu Sep 04 2014 17:00:20 GMT+0200 (Paris, Madrid (heure d’été))
903760 bps nbBlocs 77 stream window 77 - sending sendme stream received 9921654 - Buffer Amount: 0 1409842823498 Thu Sep 04 2014 17:00:23 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19069 stream length 498 Thu Sep 04 2014 17:00:23 GMT+0200 (Paris, Madrid (heure d’été))
917704 bps nbBlocs 78 stream window 78 - sending sendme stream received 10419156 - Buffer Amount: 0 1409842826501 Thu Sep 04 2014 17:00:26 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19003 stream length 498 Thu Sep 04 2014 17:00:26 GMT+0200 (Paris, Madrid (heure d’été))
930784 bps nbBlocs 79 stream window 79 - sending sendme stream received 10916658 - Buffer Amount: 3843 1409842829500 Thu Sep 04 2014 17:00:29 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18943 stream length 498 Thu Sep 04 2014 17:00:29 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 379556 dmoofmfhdLtraftfhdtfdt�$trunl% Thu Sep 04 2014 17:00:31 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379556 dmoofmfhdLtraftfhdtfdt�$trunl% Thu Sep 04 2014 17:00:31 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379556 000000646d6f6f66000000106d666864000000000000061a0000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:00:32 GMT+0200 (Paris, Madrid (heure d’été))
933752 bps nbBlocs 79 stream window 79 - sending sendme stream received 11414658 - Buffer Amount: 0 1409842833469 Thu Sep 04 2014 17:00:33 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18930 stream length 498 Thu Sep 04 2014 17:00:33 GMT+0200 (Paris, Madrid (heure d’été))
944712 bps nbBlocs 80 stream window 80 - sending sendme stream received 11912160 - Buffer Amount: 0 1409842836547 Thu Sep 04 2014 17:00:36 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18880 stream length 498 Thu Sep 04 2014 17:00:36 GMT+0200 (Paris, Madrid (heure d’été))
937696 bps nbBlocs 80 stream window 80 - sending sendme stream received 12410160 - Buffer Amount: 0 1409842841550 Thu Sep 04 2014 17:00:41 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18909 stream length 498 Thu Sep 04 2014 17:00:41 GMT+0200 (Paris, Madrid (heure d’été))
945016 bps nbBlocs 80 stream window 80 - sending sendme stream received 12908160 - Buffer Amount: 0 1409842844946 Thu Sep 04 2014 17:00:44 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18879 stream length 498 Thu Sep 04 2014 17:00:44 GMT+0200 (Paris, Madrid (heure d’été))
954584 bps nbBlocs 81 stream window 81 - sending sendme stream received 13405662 - Buffer Amount: 0 1409842848020 Thu Sep 04 2014 17:00:48 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18836 stream length 498 Thu Sep 04 2014 17:00:48 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 380091 dmoofmfhd(Ltraftfhdtfdt@$trunl� Thu Sep 04 2014 17:00:50 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 380091 dmoofmfhd(Ltraftfhdtfdt@$trunl� Thu Sep 04 2014 17:00:51 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 380091 000000646d6f6f66000000106d6668640000000000000c280000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:00:51 GMT+0200 (Paris, Madrid (heure d’été))
956792 bps nbBlocs 81 stream window 81 - sending sendme stream received 13903662 - Buffer Amount: 0 1409842851925 Thu Sep 04 2014 17:00:51 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18827 stream length 498 Thu Sep 04 2014 17:00:51 GMT+0200 (Paris, Madrid (heure d’été))
965168 bps nbBlocs 82 stream window 82 - sending sendme stream received 14401164 - Buffer Amount: 0 1409842855040 Thu Sep 04 2014 17:00:55 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18790 stream length 498 Thu Sep 04 2014 17:00:55 GMT+0200 (Paris, Madrid (heure d’été))
972752 bps nbBlocs 83 stream window 83 - sending sendme stream received 14898666 - Buffer Amount: 0 1409842858201 Thu Sep 04 2014 17:00:58 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18756 stream length 498 Thu Sep 04 2014 17:00:58 GMT+0200 (Paris, Madrid (heure d’été))
980280 bps nbBlocs 83 stream window 83 - sending sendme stream received 15396666 - Buffer Amount: 3843 1409842861324 Thu Sep 04 2014 17:01:01 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18727 stream length 498 Thu Sep 04 2014 17:01:01 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 1 6478780 dmoofmfhd �LtraftfhdtfdtF($trunl�c� Thu Sep 04 2014 17:01:08 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 6478780 dmoofmfhd �LtraftfhdtfdtF($trunl�c� Thu Sep 04 2014 17:01:13 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 6478780 000000646d6f6f66000000106d6668640000000000000af10000004c74726166000000107466686400020000000000010000 Thu Sep 04 2014 17:01:20 GMT+0200 (Paris, Madrid (heure d’été))
873344 bps nbBlocs 74 stream window 74 - sending sendme stream received 15899148 - Buffer Amount: 0 1409842881312 Thu Sep 04 2014 17:01:21 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19225 stream length 498 Thu Sep 04 2014 17:01:21 GMT+0200 (Paris, Madrid (heure d’été))
881568 bps nbBlocs 75 stream window 75 - sending sendme stream received 16396650 - Buffer Amount: 0 1409842884469 Thu Sep 04 2014 17:01:24 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19181 stream length 498 Thu Sep 04 2014 17:01:24 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 378740 dmoofmfhdLLtraftfhdtfdt.�$trunl Thu Sep 04 2014 17:01:26 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 378740 dmoofmfhdLLtraftfhdtfdt.�$trunl Thu Sep 04 2014 17:01:27 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 378740 000000646d6f6f66000000106d666864000000000000124c0000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:01:27 GMT+0200 (Paris, Madrid (heure d’été))
884808 bps nbBlocs 75 stream window 75 - sending sendme stream received 16894650 - Buffer Amount: 0 1409842888425 Thu Sep 04 2014 17:01:28 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19165 stream length 498 Thu Sep 04 2014 17:01:28 GMT+0200 (Paris, Madrid (heure d’été))
893472 bps nbBlocs 76 stream window 76 - sending sendme stream received 17392152 - Buffer Amount: 0 1409842891399 Thu Sep 04 2014 17:01:31 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19121 stream length 498 Thu Sep 04 2014 17:01:31 GMT+0200 (Paris, Madrid (heure d’été))
901584 bps nbBlocs 77 stream window 77 - sending sendme stream received 17889654 - Buffer Amount: 0 1409842894412 Thu Sep 04 2014 17:01:34 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19079 stream length 498 Thu Sep 04 2014 17:01:34 GMT+0200 (Paris, Madrid (heure d’été))
909696 bps nbBlocs 77 stream window 77 - sending sendme stream received 18387654 - Buffer Amount: 549 1409842897376 Thu Sep 04 2014 17:01:37 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19043 stream length 498 Thu Sep 04 2014 17:01:37 GMT+0200 (Paris, Madrid (heure d’été))
916848 bps nbBlocs 78 stream window 78 - sending sendme stream received 18885156 - Buffer Amount: 0 1409842900457 Thu Sep 04 2014 17:01:40 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19007 stream length 498 Thu Sep 04 2014 17:01:40 GMT+0200 (Paris, Madrid (heure d’été))
924480 bps nbBlocs 79 stream window 79 - sending sendme stream received 19382658 - Buffer Amount: 0 1409842903401 Thu Sep 04 2014 17:01:43 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18970 stream length 498 Thu Sep 04 2014 17:01:43 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 379967 dmoofmfhdTLtraftfhdtfdt>�$trunl� Thu Sep 04 2014 17:01:46 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379967 dmoofmfhdTLtraftfhdtfdt>�$trunl� Thu Sep 04 2014 17:01:46 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379967 000000646d6f6f66000000106d66686400000000000018540000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:01:47 GMT+0200 (Paris, Madrid (heure d’été))
927096 bps nbBlocs 79 stream window 79 - sending sendme stream received 19880658 - Buffer Amount: 0 1409842907225 Thu Sep 04 2014 17:01:47 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18958 stream length 498 Thu Sep 04 2014 17:01:47 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 1 4286510 dmoofmfhd�Ltraftfhdtfdt�P$trunl��� Thu Sep 04 2014 17:01:53 GMT+0200 (Paris, Madrid (heure d’été))
915000 bps nbBlocs 78 stream window 78 - sending sendme stream received 20379156 - Buffer Amount: 0 1409842913851 Thu Sep 04 2014 17:01:53 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 19015 stream length 498 Thu Sep 04 2014 17:01:53 GMT+0200 (Paris, Madrid (heure d’été))
920880 bps nbBlocs 78 stream window 78 - sending sendme stream received 20877156 - Buffer Amount: 0 1409842917040 Thu Sep 04 2014 17:01:57 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18989 stream length 498 Thu Sep 04 2014 17:01:57 GMT+0200 (Paris, Madrid (heure d’été))
926208 bps nbBlocs 79 stream window 79 - sending sendme stream received 21374658 - Buffer Amount: 0 1409842920293 Thu Sep 04 2014 17:02:00 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18962 stream length 498 Thu Sep 04 2014 17:02:00 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 380377 dmoofmfhd`LtraftfhdtfdtN $trunl� Thu Sep 04 2014 17:02:01 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 380377 dmoofmfhd`LtraftfhdtfdtN $trunl� Thu Sep 04 2014 17:02:01 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 380377 000000646d6f6f66000000106d6668640000000000001e600000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:02:02 GMT+0200 (Paris, Madrid (heure d’été))
927152 bps nbBlocs 79 stream window 79 - sending sendme stream received 21872658 - Buffer Amount: 0 1409842924402 Thu Sep 04 2014 17:02:04 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18958 stream length 498 Thu Sep 04 2014 17:02:04 GMT+0200 (Paris, Madrid (heure d’été))
930368 bps nbBlocs 79 stream window 79 - sending sendme stream received 22370658 - Buffer Amount: 0 1409842928031 Thu Sep 04 2014 17:02:08 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18944 stream length 498 Thu Sep 04 2014 17:02:08 GMT+0200 (Paris, Madrid (heure d’été))
936056 bps nbBlocs 80 stream window 80 - sending sendme stream received 22868160 - Buffer Amount: 0 1409842931116 Thu Sep 04 2014 17:02:11 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18916 stream length 498 Thu Sep 04 2014 17:02:11 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 379185 dmoofmfhd$�Ltraftfhdtfdt]�$trunl� Thu Sep 04 2014 17:02:14 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379185 dmoofmfhd$�Ltraftfhdtfdt]�$trunl� Thu Sep 04 2014 17:02:14 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379185 000000646d6f6f66000000106d66686400000000000024840000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:02:14 GMT+0200 (Paris, Madrid (heure d’été))
937176 bps nbBlocs 80 stream window 80 - sending sendme stream received 23366160 - Buffer Amount: 0 1409842935133 Thu Sep 04 2014 17:02:15 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18911 stream length 498 Thu Sep 04 2014 17:02:15 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 1 2851085 dmoofmfhd �Ltraftfhdtfdt-�x$trunl� �� Thu Sep 04 2014 17:02:18 GMT+0200 (Paris, Madrid (heure d’été))
932800 bps nbBlocs 79 stream window 79 - sending sendme stream received 23864658 - Buffer Amount: 3843 1409842940344 Thu Sep 04 2014 17:02:20 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18934 stream length 498 Thu Sep 04 2014 17:02:20 GMT+0200 (Paris, Madrid (heure d’été))
937080 bps nbBlocs 80 stream window 80 - sending sendme stream received 24362160 - Buffer Amount: 0 1409842943656 Thu Sep 04 2014 17:02:23 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18912 stream length 498 Thu Sep 04 2014 17:02:23 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 379903 dmoofmfhd*�Ltraftfhdtfdtm`$trunl Thu Sep 04 2014 17:02:25 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379903 dmoofmfhd*�Ltraftfhdtfdtm`$trunl Thu Sep 04 2014 17:02:25 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 379903 000000646d6f6f66000000106d6668640000000000002a8f0000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:02:26 GMT+0200 (Paris, Madrid (heure d’été))
936560 bps nbBlocs 80 stream window 80 - sending sendme stream received 24860160 - Buffer Amount: 3843 1409842948025 Thu Sep 04 2014 17:02:28 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18914 stream length 498 Thu Sep 04 2014 17:02:28 GMT+0200 (Paris, Madrid (heure d’été))
940504 bps nbBlocs 80 stream window 80 - sending sendme stream received 25358160 - Buffer Amount: 0 1409842951372 Thu Sep 04 2014 17:02:31 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18898 stream length 498 Thu Sep 04 2014 17:02:31 GMT+0200 (Paris, Madrid (heure d’été))
945176 bps nbBlocs 80 stream window 80 - sending sendme stream received 25856160 - Buffer Amount: 0 1409842954520 Thu Sep 04 2014 17:02:34 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18878 stream length 498 Thu Sep 04 2014 17:02:34 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 1 1940806 dmoofmfhd+�Ltraftfhdtfdt=�$trunl�� Thu Sep 04 2014 17:02:36 GMT+0200 (Paris, Madrid (heure d’été))
onsegment track 2 378750 dmoofmfhd0�Ltraftfhdtfdt}$trunl} Thu Sep 04 2014 17:02:36 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 378750 dmoofmfhd0�Ltraftfhdtfdt}$trunl} Thu Sep 04 2014 17:02:36 GMT+0200 (Paris, Madrid (heure d’été))
appending track 2 378750 000000646d6f6f66000000106d66686400000000000030b90000004c74726166000000107466686400020000000000020000 Thu Sep 04 2014 17:02:36 GMT+0200 (Paris, Madrid (heure d’été))
938456 bps nbBlocs 80 stream window 80 - sending sendme stream received 26354160 - Buffer Amount: 3843 1409842960331 Thu Sep 04 2014 17:02:40 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18906 stream length 498 Thu Sep 04 2014 17:02:40 GMT+0200 (Paris, Madrid (heure d’été))
942448 bps nbBlocs 80 stream window 80 - sending sendme stream received 26852160 - Buffer Amount: 0 1409842963608 Thu Sep 04 2014 17:02:43 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18890 stream length 498 Thu Sep 04 2014 17:02:43 GMT+0200 (Paris, Madrid (heure d’été))
946184 bps nbBlocs 81 stream window 81 - sending sendme stream received 27349662 - Buffer Amount: 0 1409842966913 Thu Sep 04 2014 17:02:46 GMT+0200 (Paris, Madrid (heure d’été))
sendme timeout 18870 stream length 498 Thu Sep 04 2014 17:02:46 GMT+0200 (Paris, Madrid (heure d’été))
send db_end CID 1 sid 1 reason 1 Thu Sep 04 2014 17:02:47 GMT+0200 (Paris, Madrid (heure d’été))
stop streaming Thu Sep 04 2014 17:02:47 GMT+0200 (Paris, Madrid (heure d’été))
execute fin Thu Sep 04 2014 17:02:47 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 4286510 dmoofmfhd�Ltraftfhdtfdt�P$trunl��� Thu Sep 04 2014 17:02:54 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 4286510 000000646d6f6f66000000106d66686400000000000015df0000004c74726166000000107466686400020000000000010000 Thu Sep 04 2014 17:02:59 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 2851085 dmoofmfhd �Ltraftfhdtfdt-�x$trunl� �� Thu Sep 04 2014 17:03:01 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 2851085 000000646d6f6f66000000106d66686400000000000020cd0000004c74726166000000107466686400020000000000010000 Thu Sep 04 2014 17:03:04 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 1940806 dmoofmfhd+�Ltraftfhdtfdt=�$trunl�� Thu Sep 04 2014 17:03:06 GMT+0200 (Paris, Madrid (heure d’été))
appending track 1 1940806 000000646d6f6f66000000106d6668640000000000002b940000004c74726166000000107466686400020000000000010000 Thu Sep 04 2014 17:03:08 GMT+0200 (Paris, Madrid (heure d’été))

**Comment by cconcolato** [comment]
Do you still have this issue?

**Comment by Ayms** [comment]
I don't know, can't test it right now, maybe you can close it for now.
