### ISSUE TITLE
README refers to getArrayBuffer

### ISSUE THREAD

**Issue by mthaddon** [gpac/mp4box.js#161]
In the README.md there's a reference to

```
var ab = getArrayBuffer();
```

However, it's not clear whether this is a custom function or whether it should be a regular ArrayBuffer.

Happy to submit a doc fix if someone can clarify.

**Comment by cconcolato** [comment]
Thanks for the report. getArrayBuffer is not a method provided by mp4box.js. It is typically provided by the application, and returns an ArrayBuffer containing the ISOBMFF data to be parsed. I modified the readme for that reopen if this is not clear enough.
