### ISSUE TITLE
Memory usage loading a file

### ISSUE THREAD

**Issue by mthaddon** [gpac/mp4box.js#162]
I'm trying to extract data from large video files, and have that portion working very well. The problem is, memory usage in the browser seems to match the size of the file I'm loading. I'm using the example readBlock function from the ui-helper.js.

I tried moving the FileReader object (r) to be outside of the readBlock function, but I'm still seeing the same memory usage.

I've got an example of the code available https://haddons.net/mp4box.js/ with a sample 208MB file to test with.

To reproduce, load that page in a new browser tab, open the developer tools and take a memory snapshot. Then select a large video file and wait for it to be parsed. Then take another memory snapshot and you'll see the browser is using slightly more memory than the file size primarily for ArrayBuffers.

**Comment by mthaddon** [comment]
I've tried using _keepMdatData false in MP4Box.createFile, but in that case I don't seem to get the extracted data I need.

**Comment by mthaddon** [comment]
So I've worked around this by using setting _keepMdatData false (i.e. `MP4Box.createFile(false)`), and doing two passes on the file - this allows me to get the data I need. I'm not sure if that's the best way to do it though.

**Comment by cconcolato** [comment]
Thanks for the report. I can indeed reproduce the problem. 
mp4box.js cannot know when the application will not need the media data anymore. It needs to be told. This can be done either at the file creation (`keepMdatData`) or later using `releaseUsedSamples` or using `flush`. 
That said, there is something weird happening with your file:

If I change your onReady to:
```
mp4boxfile.onReady = function(info) {
    for (var i = 0; i < info.tracks.length; i++){
      mp4boxfile.setExtractionOptions(info.tracks[i].id, null, { nbSamples: info.tracks[i].nb_samples });
    }
    mp4boxfile.start();
};
```
and your onSamples to:
```
mp4boxfile.onSamples = function(id, user, samples) {
      mp4boxfile.releaseUsedSamples(id, samples[samples.length-1].number);
      return;
}
```
*and* if I reimport your file with MP4Box (binary from GPAC), I get a memory usage that goes from 5MB to 9MB. 
But if I do it with your original file, the memory indeed goes from 5MB to 216MB.
I need to investigate bit more...

**Comment by dustinkerstein** [comment]
Just wanted to check on this. Were either of you able to figure out the cause of this memory usage? I'm curious if this may be related to #196 (which happens during segmentation).

**Comment by cconcolato** [comment]
Closing this issue as it seems stale. FYI, some documentation on memory management is available here: https://github.com/gpac/mp4box.js/wiki/Memory-managment-in-MP4Box.js
