### ISSUE TITLE
Support for heic/heif read ?

### ISSUE THREAD

**Issue by bciceron** [gpac/mp4box.js#163]
Hello is there a plan to support HEIF/HEIC , please ?

**Comment by cconcolato** [comment]
Basic support for the boxes is here. And yes, it shouldn't be too hard to integrate with an HEVC decoder, just like we did for the AV1 decoder. Note that NokiaTech has a JS player here http://nokiatech.github.io/heif/index.html

**Comment by cconcolato** [comment]
There is also https://github.com/strukturag/libheif.
