### ISSUE TITLE
[Question] Can I obtain priming and remaining sample counts?

### ISSUE THREAD

**Issue by tgrajewski** [gpac/mp4box.js#165]
Advanced Audio Coding (.m4a) files contain encoder padding as explained in [this Apple documentation](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFAppenG/QTFFAppenG.html).

![aac_encoded_bit_stream](https://user-images.githubusercontent.com/4324821/53035292-6877a400-3475-11e9-8256-99965d86c6f5.jpg)

The `afinfo` utility on mac OS can extract length of these paddings, below is an example output of `afinfo`:

![afinfo](https://user-images.githubusercontent.com/4324821/53035348-7f1dfb00-3475-11e9-923b-37728553c273.png)

Can mp4box.js be used to obtain these numbers? If yes, then any pointers appreciated.

**Comment by rbouqueau** [comment]
I see you've closed the issue. Have you found an answer?

**Comment by tgrajewski** [comment]
Unfortunately no answer yet. I've closed the question because no one answered, so I though that no one knows or there is not enough activity on the project.
