### ISSUE TITLE
Player that performs on-the-fly fragmentation is not working

### ISSUE THREAD

**Issue by evgeny-nadymov** [gpac/mp4box.js#166]
Could you please fix https://gpac.github.io/mp4box.js/test/index.html? It seems that there is no way to use player anymore.

**Comment by tbranyen** [comment]
I went through the commits, looks like:

1005056db1f268aa890c1ec0862378ffccd11ae8 is the breaking commit and
46f918b5323b0c6e95fdf2ea8705c4a4e3a25e98 is the last working (and most stable) commit

**Comment by tbranyen** [comment]
Wow! By merely reverting that commit, I've fixed all my issues with playback locally. This should really really be reverted and re-patched once the logic is correct.

@rbouqueau any thoughts on this?

**Comment by evgeny-nadymov** [comment]
Thank you a lot for this investigation!

**Comment by tbranyen** [comment]
Opened a revert PR here #170

**Comment by tbranyen** [comment]
Turns out no revert was necessary, but I did apply the required patch in #172

**Comment by cconcolato** [comment]
Thanks to @tbranyen the player is working, at least for the first 4 examples (that have HTTPS URLs). Reopen if not working.

**Comment by evgeny-nadymov** [comment]
Thanks a lot!
