### ISSUE TITLE
Confusing discrepancies between require methods

### ISSUE THREAD

**Issue by JuanIrache** [gpac/mp4box.js#176]
Hi,

I found that the library behaves differently depending on how you require it.

- Option 1: Following instructions from the NPM page https://www.npmjs.com/package/mp4box
```
var MP4Box = require('mp4box').MP4Box;
var mp4box = new MP4Box();
etc...
```
Trying to read large files crashes in some browsers (Chrome) when running the example at http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html

- Option 2: Following instructions from the GitHub page https://github.com/gpac/mp4box.js (why are they different in the first place?)
```
MP4Box = require('mp4box');
mp4boxfile = MP4Box.createFile();
```
> TypeError: MP4Box.createFile is not a function

- Option 3: Using the prebuilt mp4box.all.js
```
MP4Box = require('../../node_modules/mp4box/dist/mp4box.all.js')
mp4boxFile = MP4Box.createFile(false);
```

> TypeError: MP4Box.createFile is not a function

- Option 4: Downloaded the mp4box.all.js file from the working example http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html and included it via html

`<script src="./mp4box.all.js"></script>`

`mp4boxFile = new MP4Box(false);`

This combination works fine with large files!

I might be missing something.

**Comment by JuanIrache** [comment]
Here's my progress so far:

The NPM package is incredibly outdated (2016). In order to install the current version, you can do

> npm install gpac/mp4box.js

But that will not run out of the box. You must manually install the dependencies (not sure why)

> cd node_modues/mp4box/
> npm install

And build the package (install grunt-cli first if you don't usually use it)

> npm install -g grunt-clil
> grunt

Then you can use
`var MP4Box = require('mp4box');
`

There must be a way to automate all this. Is the NPM package not supported anymore?

**Comment by tbranyen** [comment]
@JuanIrache right now I've been using `@tbranyen/mp4box` and publishing my own builds. Until this package gets bumped, you may consider doing the same to avoid the secondary install step.

**Comment by JuanIrache** [comment]
@tbranyen Sounds great. Will try it out. Thanks

**Comment by cconcolato** [comment]
Thanks for the report. The sync between GitHub and npm was not working, for a while. Sorry for the confusion. It should be fixed now. v0.3.19 is on npm, see https://www.npmjs.com/package/mp4box. Reopen if not working.
