### ISSUE TITLE
Using dash.js along with mp4box.js

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#18]
Do you think it is possible to combine the two and create a simple dash player (only one bit rate) with the (roughly) following steps:

1) Get the non-fragmented source and create an .mpd (of the fragmented) file from it.
2) Replace the source with the .mpd file.
3) Override  fragmentLoader.js of dash.js so that when trying to download a segment it will download the matching parts of the non-fragmented mp4 pass it to mp4box and get the correct chunks to as a respond.

What do you think? is there a way to combine the two projects?
That is - to utilize the strength of dash.js with playing a stream (even with only one bit rate) with the possibility of creating the fragmented file on the fly?

**Comment by nickgarver** [comment]
did you figure this out at all? this is waht I am trying to do as well

**Comment by ockulkarni** [comment]
Did Anyone figure it out? stucked in same problem

**Comment by ockulkarni** [comment]
Do reply on email (ockulkarni18@gmail.com)

**Comment by rbouqueau** [comment]
I made a simple search on the dash.js repo and found this: https://github.com/Dash-Industry-Forum/dash.js/pull/595

Does it help?

**Comment by cconcolato** [comment]
Generally I think it should be possible to integrate mp4box.js with dash.js or other players.
