### ISSUE TITLE
Last samples are not parsed

### ISSUE THREAD

**Issue by kay-master** [gpac/mp4box.js#180]
Am failing to get the last samples parsed, I don't know if it's the way am appending or what but the last few samples are not parsed.

Using FF, 66.0.3 (64-bit) and Chrome, 74.0.3729.169 (Official Build) (64-bit),

Here is my test code and test video, [Test Code](https://drive.google.com/open?id=1b-FXwodXAFq_hZ347nkpCr5vJyWMF2YW) and [Test Video](https://drive.google.com/open?id=1g1mZy-txKFqUlk4yUNTrQvfB2Je6cCEb), using the latest mp4box release 0.3.20.

This is the same issue from 2014 #25, but maybe it's an issue with my code

**Comment by AndyLuuuuu** [comment]
I am having same problem, same issue as #25

**Comment by cconcolato** [comment]
It's possible that this issue was fixed in the recent commits. Can you check?
