### ISSUE TITLE
Dependency is not satisfiable: libavcodec-ffmpeg56

### ISSUE THREAD

**Issue by hutber** [gpac/mp4box.js#182]
I am running Mint version 19.1 which I believe is fairly common.

When trying to install the deb its meeting dependency problems. 

`Dependency is not satisfiable: libavcodec-ffmpeg56 (>= 7:2.4)|libavcodec-ffmpeg-extra56 (>= 7:2.4)`

I do have ffmpeg57 installed, so do I need the extra 56 to get this working?

`libavcodec-extra is already the newest version (7:3.4.6-0ubuntu0.18.04.1).
libavcodec-extra57 is already the newest version (7:3.4.6-0ubuntu0.18.04.1).`

**Comment by cconcolato** [comment]
This is the wrong repository for this bug report.
