### ISSUE TITLE
Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by miguelBinpar** [gpac/mp4box.js#184]
I'm getting this error:

```bash
Cannot read property 'entries' of undefined TypeError: Cannot read property 'entries' of undefined
    at Function.ISOFile.setSampleGroupProperties (/bundle/bundle/programs/server/npm/node_modules/mp4box/dist/mp4box.all.js:6993:70)
    at [object Object].ISOFile.buildTrakSampleLists (/bundle/bundle/programs/server/npm/node_modules/mp4box/dist/mp4box.all.js:7208:12)
    at [object Object].ISOFile.buildSampleLists (/bundle/bundle/programs/server/npm/node_modules/mp4box/dist/mp4box.all.js:7047:8)
    at [object Object].ISOFile.appendBuffer (/bundle/bundle/programs/server/npm/node_modules/mp4box/dist/mp4box.all.js:6088:9)
```

We just discovered we've been having this problem for a few months now.

We always had version set to `^0.3.15` so we think it might be related to latest versions published since April '19.

The thing is only failing at our server (ubuntu 1604) but working on our local machines (different versions of macOS, including latest).

Doest it make any sense to you? Has anyone faced a similar problem?

It seems easy to check `sbgp` property before using `sbgp.entries` but is it a real solution?

**Comment by cconcolato** [comment]
It'd be interesting to get an example of file that produces this error. I'd like to understand why it fails.

**Comment by cconcolato** [comment]
Re-open if you have a file to share.

**Comment by Haganophosphate** [comment]
I had this was in setSampleGroupProperties. I added if (k == 'insert') continue to fix after this line:

for (k in sample_groups_info) {
		if (k == 'insert') continue;

**Comment by cconcolato** [comment]
@JesseNReynolds Thanks for the file. I just tried it in https://gpac.github.io/mp4box.js/test/filereader.html and I don't get any error message. Can you update to the latest MP4Box.js and double check?

**Comment by JesseNReynolds** [comment]
@Haganophosphate i appreciate the information. How did you end up moving the codec information to the front of the file?

**Comment by Haganophosphate** [comment]
I used a thing called qtfaststart.java on android

**Comment by cconcolato** [comment]
Can you share a file that doesn't work?
