### ISSUE TITLE
How can I mux raw h264 frames into a non-fragmented mp4 like native MP4Box

### ISSUE THREAD

**Issue by EddaAkikusa** [gpac/mp4box.js#185]
I can mux raw h264 frames into a non-fragmented mp4 file via
`MP4Box -add video.h264 video.mp4`
How can I do the same thing via `mp4box.js`?

**Comment by cconcolato** [comment]
As responded in #230, mp4box.js does not have the parser for H264, but if you have it using [this code ](https://github.com/gpac/mp4box.js/blob/master/src/isofile-advanced-creation.js) you should be able to create a track, in theory, but I did not have chance to try that.
