### ISSUE TITLE
Dependency on npm

### ISSUE THREAD

**Issue by jwagner** [gpac/mp4box.js#187]
mp4box.js depends on npm. Via `package.json`:
`    "npm": "^6.9.0"`

Is this necessary? I can't find any reference to it actually using the dependency.

**Comment by vsemaphore** [comment]
I browser tough codebase and I cannot find any usage of it. And npm package adds 34MB.

**Comment by cconcolato** [comment]
I removed the dependency from the package.json file. Reopen the issue if it does not solve your problem.
