### ISSUE TITLE
Inspector: Frames per second

### ISSUE THREAD

**Issue by cthurston** [gpac/mp4box.js#189]
Can the fps be derived from the video information provided from the inspector?

If not is it a difficult thing to add?

**Comment by cconcolato** [comment]
It can be done for some files:
* Get moov/mvex/trex/default_sample_duration (e.g. 1001)
* Get moov/trak/mdia/mdhd/timescale (e.g. 24000)
The frame rate is timescale/default_sample_duration (e.g. 24000/1001)
