### ISSUE TITLE
How to segment video with moov at the end of the file?

### ISSUE THREAD

**Issue by stephanos** [gpac/mp4box.js#190]
I've spent a few hours on this and read every issue I could find, but I still don't know how to solve this problem.

My video file - [small.mp4](https://github.com/gpac/mp4box.js/files/4384870/small.mp4.zip) - looks like this:
<img width="143" alt="Screen Shot 2020-03-25 at 20 36 48" src="https://user-images.githubusercontent.com/159852/77607747-8a452500-6ed8-11ea-871c-1e178879a56e.png">

When I try to segment it with mp4box.js I, sure enough, get the file information, but I never get any segments.

It works when I use a video with the `moov` segment at the beginning, though.

So my question is: **does mp4box work for files with the moov at the end? Or am I doing anything wrong?**

**Comment by stephanos** [comment]
Here's my code:

```
const handleFileChange = async (evt) => {
  const mp4boxfile = MP4Box.createFile()
  mp4boxfile.onError = function(e) {
    console.error(e)
  }
  mp4boxfile.onReady = function(info) {
    console.log(info)
    const options = { nbSamples: 1000 }
    mp4boxfile.setSegmentOptions(info.tracks[0].id, null, options)
    const initSegs = mp4boxfile.initializeSegmentation()
    console.log(initSegs)
    mp4boxfile.start()
  }
  mp4boxfile.onSegment = function (id, user, buffer) {
    console.log("Received segment on track "+id+" for object "+user+" with a length of "+buffer.byteLength);
  }

  const file = evt.target.files[0]
  const size = file.size

  function readFile(done) {
    let offset = 0
    let chunk_size = Math.pow(2, 13)
    const reader = new FileReader()
    reader.onloadend = function(e){
      if (e.target.readyState == FileReader.DONE){
        let buffer = e.target.result
        buffer.fileStart = offset
        mp4boxfile.appendBuffer(buffer)
        if (offset < size) {
          offset += chunk_size
          console.log(offset)
          var blob = file.slice(offset, Math.min(size, offset + chunk_size))
          reader.readAsArrayBuffer(blob)
        } else {
          mp4boxfile.flush()
        }
      }
    }
    var blob = file.slice(offset, offset + chunk_size)
    reader.readAsArrayBuffer(blob)
  }
  readFile()
}
```

**Comment by cconcolato** [comment]
There was a bug in mp4box.js. Fixed with https://github.com/gpac/mp4box.js/commit/2bfb7a53d8a66db846c26375c2693de1b7cd4c5b. Reopen the issue if this is not the case.
