### ISSUE TITLE
onSegment audio sample flushing hangs up when samples split across buffers

### ISSUE THREAD

**Issue by pmccarter** [gpac/mp4box.js#191]
Encountering an issue when audio samples are split across buffers. The getSample() function in isofile-sample-processing.js will return null even when the complete sample is inside mp4box buffers. If this is the last buffer to be appended then that and subsequent samples will never be flushed through the onSegment callback.

Why doesn't getSample() attempt to load the full sample from memory, instead deferring to a future processSamples() call that might never occur? It seems like even a call to flush() could get hung up in a similar way. Is there a usage pattern of calling flush() until all buffered samples are processed?

**Comment by cconcolato** [comment]
This should be fixed with https://github.com/gpac/mp4box.js/commit/2bfb7a53d8a66db846c26375c2693de1b7cd4c5b. Please reopen if this is not the case.
