### ISSUE TITLE
MP4Box emsg boxes v1 support

### ISSUE THREAD

**Issue by nicoweilelemental** [gpac/mp4box.js#192]
Hello team,

We did some work with emsg boxes v1 to support KLV metadata but the analysis in MP4Box doesn't report the expected information:
- no presentation_time box
- scheme_id_uri is empty
- value is empty

When we switch the emsg boxes version to zero, all information is properly located.

I uploaded the index_video_1_0_1.mp4 sample on mediafire

Thanks,
Nicolas

**Comment by rbouqueau** [comment]
This issue seems to have been transfered to the gpac project and fixed by https://github.com/gpac/gpac/commit/4ee02fbb73507dcb97c78cc9e5c54470ceda949c. Please close if ok!

**Comment by nicoweilelemental** [comment]
Will this change be reflected in mp4box.js ?

**Comment by jeanlf** [comment]
should now be fixed in mp4box.js thanks for the report

**Comment by nicoweilelemental** [comment]
Hi Jean, thanks for the quick turnaround. Everything looks good in mp4box.js apart from the field "presentation_time_delta" which should be labeled "presentation_time". I guess the value for this field is correct, as I see the expected values for the scheme_id_uri and value fields.
