### ISSUE TITLE
How can I get video fps by mp4box.js?

### ISSUE THREAD

**Issue by numberwolf** [gpac/mp4box.js#193]
I have checked 'info.videoTracks' and 'info.tracks', here's no frame rate information. 
So, have here another way to get fps information?

Thanks.

**Comment by numberwolf** [comment]
I have got fps value by nb_samples and duration(after timescale).

**Comment by jeanlf** [comment]
that's the correct way to get an estimate of the framerate, isobmff does not carry any fps information, only sample durations (which may be constant or not) and timescales.
