### ISSUE TITLE
Zero memory copy optimizations

### ISSUE THREAD

**Issue by asbai** [gpac/mp4box.js#194]
I think at least the following points can be optimized

1: ArrayBufferView classes like Uint8Array can be used to slice part of a buffer with zero copy. For example: 
```javascript
var part = new Uint8Array(buffer, 32, 64);
```
`buffer` in the above example is a ArrayBuffer, and the new Uint8Array view object `part[0] == buffer[32]`  (i.e.: `part.byteOffset == 32`), and `part.length == 64`.

Using this technique, we can achieve zero-copy data slicing。

2: Blob can gather multiple peaces of ArrayBufferView to a big, readable stream without memory allocation and copy. So we can use it to concat multiple buffers with zero copy.

Alternatively, just put multiple ArrayBufferView (Uint8Array) to a regular array (e.g.: `array.push(part)`), and we can add every Uint8Array in this array to a sourceBuffer one by one later.

3: The `appendBuffer` API also need to support an Uint8Array object as the input data. In this way, in many cases, we can avoid the extra memory copy in order to prepare the `data` parameter.

**Comment by rbouqueau** [comment]
Hi, thank you for the proposal. This project is actually undermaintained because we lack time. So any contribution is highly welcome, and we take care to review and integrate the pull requests. Do you think you could adapt the code according to your suggestion?

**Comment by asbai** [comment]
Not sure, I am not familiar with the format of mp4 files. And this project seem very complicated (there are many js files). 

Emmmm.... may be I can give it a try...

**Comment by cconcolato** [comment]
I added documentation on how we manage memory today: https://github.com/gpac/mp4box.js/wiki/Memory-managment-in-MP4Box.js. Maybe it can help.

**Comment by asbai** [comment]
OK, Thanks. We'll learn it ASAP :-)
