### ISSUE TITLE
Create mp4 file from hls fragment

### ISSUE THREAD

**Issue by supersh86** [gpac/mp4box.js#198]
Hello everyone. Recently I set out to create an mp4 file from a fragment in hlsjs.

When playing a video, hls.js creates separate pieces of audio and video.
H264 and AAC
They are stored as Uint8Array.
Is it possible to take Uint8Array from fragment 1, and mux them into one mp4?

**Comment by cconcolato** [comment]
Theoretically, you could with the code [here](https://github.com/gpac/mp4box.js/blob/master/src/isofile-advanced-creation.js) but that is assuming you know the properties of the samples (random access points, ...).
