### ISSUE TITLE
Performances problem

### ISSUE THREAD

**Issue by Ayms** [gpac/mp4box.js#20]
Related to #16 stop/restart

Tested with Peersm and http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/

As you can see on the screenshot the average rate for Peersm to retrieve the data before passing it to mp4box is 1 Mbps, the rate for mp4box to issue segments continuously decreases (14650 bps after 49838 s on the screenshot)

There is no memory leak but maybe there is an excessive number of JSArrayBufferData and some lookup inside them are causing the performance problem.

![mp4boxperf](https://cloud.githubusercontent.com/assets/759202/4372350/5719f9d0-4323-11e4-9329-d9533a02cc86.png)

**Comment by cconcolato** [comment]
How can I reproduce your problem? Are you always feeding byte buffers at a regular pace, with buffers of the same size? How do you monitor the output data rate of MP4box.js? By measuring the segment lengths and dividing by the elapsed time between segment callbacks? Do you think I can reproduce it by feeding a large file with small chunks and monitoring the result?

**Comment by Ayms** [comment]
Yes, you should be able to reproduce it easily, for my tests Peersm was downloading a large file at a rate ~1 Mbps and passing the chunks (512 B if I remember well) to mp4box, then measuring the rate in the mp4box output

**Comment by cconcolato** [comment]
Closing the issue as this is old and performance has changed. Open a new issue if you still have perf problems.
