### ISSUE TITLE
Question: Processing MPD segments

### ISSUE THREAD

**Issue by interpegasus** [gpac/mp4box.js#203]
I would like to know if there is an example, on how to process an DASH file manifest with mp4box.js, and getting data from each segment?
Thank you

**Comment by cconcolato** [comment]
mp4box.js is about processing ISOBMFF-based files. It does not handle manifests formats (DASH, HLS, or else). For MPD manifest processing, you should check https://github.com/Dash-Industry-Forum/dash.js.
