### ISSUE TITLE
Bug: Small chunk size will not fire "onSamples"

### ISSUE THREAD

**Issue by motoyasu-yamada** [gpac/mp4box.js#205]
When "the sample does not end in this buffer" in function "ISOFile.getSample", subsequent partials will not be loaded. Then "getSmaple" return null.

`processSamples `  function in `isofile.js` receive null and so will not fire "onSamples".

```js
ISOFile.prototype.processSamples = function(last) {
:
				var sample = this.getSample(trak, trak.nextSample);
				if (sample) {
					trak.nextSample++;
					extractTrak.samples.push(sample);
				} else {
					break;
				}
```

**Comment by dalecurtis** [comment]
Awesome, thanks for the fix!

**Comment by dalecurtis** [comment]
Bump @cconcolato since a lot of folks hit this issue when trying to use the streaming API.

**Comment by cconcolato** [comment]
The issue should be fixed with https://github.com/gpac/mp4box.js/commit/2bfb7a53d8a66db846c26375c2693de1b7cd4c5b. Please open a new issue if this is not the case.

**Comment by elhigu** [comment]
Is this already released in npm? I could try it out.
