### ISSUE TITLE
Question:MSE support on iPhone?

### ISSUE THREAD

**Issue by pelnar** [gpac/mp4box.js#207]
Hi,
Is there any way to make the Media source based playback available on iPhone  - safari, Ff or chrome?
I am able to use this great library to extract 2 videos from a single video file,steam and play simultaneously. But this does not work on iPhone.
At the point where the .ms property is accessed on video element it fails, because ms is undefined..
Thanks!

**Comment by cconcolato** [comment]
Looking at https://caniuse.com/?search=media%20source it seems it's only supported in iPadOS 13 and later. Not sure the library can help at the moment.
