### ISSUE TITLE
Emsgbox v1 label for presentation_time

### ISSUE THREAD

**Issue by nicoweilelemental** [gpac/mp4box.js#213]
Currently the web interface displays "presentation_time_delta" while it should be "presentation_time" with emsg boxes v1.
Sample attached:
[index_video_1_0_2738426.zip](https://github.com/gpac/mp4box.js/files/5367690/index_video_1_0_2738426.zip)

**Comment by cconcolato** [comment]
Fixed. Thanks for the report.

**Comment by nicoweilelemental** [comment]
All good, @cconcolato , thanks!
