### ISSUE TITLE
hevcimageviewer test example is not working

### ISSUE THREAD

**Issue by adamsvystun** [gpac/mp4box.js#219]
hevcimageviewer test example is not working. Niether the [demo](http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/hevcimageviewer/) that was linked in the issue #76 , nor the version from master.

Is there a working version of the demo?

**Comment by cconcolato** [comment]
Thanks for the report. Sorry for the issue. This is an old example, not maintained anymore. You should have a look at other projects like https://github.com/strukturag/libheif
