### ISSUE TITLE
I use the appendBuffer, but can not receive video samples?

### ISSUE THREAD

**Issue by numberwolf** [gpac/mp4box.js#220]
eg:
// stream len = 1000
stream.fileStart = 0; 
this.mp4box1.appendBuffer(stream);
// ...
// then
stream2.fileStart = stream.byteLength; 
this.mp4box1.appendBuffer(stream2);

But I only receive the audio samples, without video samples.

When I push whole mp4 bytes into mp4box.js,  I can receive the video samples and audio samples.

thx.

**Comment by numberwolf** [comment]
when moov box in end of file, this bug happened

**Comment by cconcolato** [comment]
Can you double-check now? This should be fixed with with this commit https://github.com/gpac/mp4box.js/commit/2bfb7a53d8a66db846c26375c2693de1b7cd4c5b. Reopen with more details and an example file if it is not working.

**Comment by numberwolf** [comment]
Thx，I will retry it with new commit~
