### ISSUE TITLE
Version of sidx set to 0 on write

### ISSUE THREAD

**Issue by nklhrstv** [gpac/mp4box.js#227]
Version of [sidx](https://github.com/gpac/mp4box.js/blob/9f7b7f73c56fa33fc4cc9ec4c9fd535585c560a0/src/writing/sidx.js#L2) and a few other atoms version set to 0 on write even if it was parsed as 1.
What is the reason for this behavior?

**Comment by cconcolato** [comment]
> What is the reason for this behavior?

64-bit numbers were not simple to handle 6 years ago when that code was written. I think there are clean ways to handle them now, I need to check. Do you still have the need for it?

**Comment by nklhrstv** [comment]
Hi @cconcolato i'm using different library to parse mp4 files now. Thank you! You can close this issue.
