### ISSUE TITLE
Videos that are not working on the demo

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#23]
Since I'm extensively testing the demo app behaviour and benchmarks on many videos these days, I have decided to open an issue that will have all the videos that I found that are not working.

If anyone knows why / has more videos to share , please comment here.

This is the first one 
http://content.jwplatform.com/videos/HkauGhRi-640.mp4

**Comment by cconcolato** [comment]
The latest commits fix the playback of this video. That was a nasty bug that had me rewrite a part of the code. Thanks for the report.

**Comment by guypaskar** [comment]
Another file (sintel) I'm not sure what's wrong with it.

http://storage.googleapis.com/peer5_vod/sintel-2048-surround.mp4

**Comment by cconcolato** [comment]
Both links on this page works with the new version. I'm closing the issue. Reopen if it's not the case or if other videos don't work.
