### ISSUE TITLE
Move the Moov

### ISSUE THREAD

**Issue by marklundin** [gpac/mp4box.js#235]
Is there a fast way to move the moov atom in a file to the begging? SOme mp4's I'm using have their moov at the end, which causes issues. It seems like it should've possible to shift this to the beginning, but I'm struggling to understand how to do this.

**Comment by cconcolato** [comment]
If you want to do it on-the-fly, in the browser, MP4Box.js can do that, but not simply. MP4Box.js can fragment a file for use with HTML5 Media Source Extension, see for example https://github.com/gpac/mp4box.js/blob/master/test/file-segmenter.html. If you can use a command-line tool, [MP4Box](https://github.com/gpac/gpac/wiki/MP4Box) (not this Javascript version) can do that pretty easily, simply import the file: `MP4Box -add in.mp4 out.mp4`.
