### ISSUE TITLE
Figure out best parameters to use

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#24]
There is significant performance changes when using different parameters (mainly different chunk size and different segment duration) - By performance I mean load time of the video and seek durations.

i.e when reducing the segment duration the video loads faster but can be stuck very fast. when increasing it, it takes time for the video to load but when it starts playing it should be Ok.

What would be a good way to decide the optimum for a specific video?

**Comment by cconcolato** [comment]
I just added in 90c67b1827 bit rate information for the file and per track. This should give you an indication of the minimum chunk size and download period that is needed to avoid the video getting stuck. The segment size should not have impact (except on the processing by the browser, but in the latest test with 1 frame = 1 segment I did not notice any problem). HTH.
