### ISSUE TITLE
some mp4 videos can't get any feedback

### ISSUE THREAD

**Issue by JefferyHo** [gpac/mp4box.js#240]
when I put some mp4 videos in my web or [site](https://gpac.github.io/mp4box.js/test/filereader.html). I can't get any feedback. 
It could not go into  onReady or onError, when I check the video info with VLC player, it shows:
![image](https://user-images.githubusercontent.com/44078665/128862128-7d8e994e-e5f9-415f-90e6-30cc9563bd6e.png)

and then I logged, it enter the code:
![image](https://user-images.githubusercontent.com/44078665/128862427-10700090-a98d-4bb0-aeed-8cbd5337234c.png)
(I add the onError code myself which solved my problems somehow)

And when I put the file into web video, It can't play. I just hope I can get  any feedback ( onReady or onError)

**Comment by cconcolato** [comment]
I'm not sure I understand this error report. Can you share a file that produces this problem?

**Comment by cconcolato** [comment]
Closing this issue as it seems to be stale. Reopen it if you have more details.
