### ISSUE TITLE
The last few samples can't be parsed, even after the whole file has been downloaded.

### ISSUE THREAD

**Issue by olizax** [gpac/mp4box.js#25]
![mp4box](https://cloud.githubusercontent.com/assets/1644868/5431563/db6548dc-8466-11e4-9c24-9ddecc1b63e4.png)

**Comment by cconcolato** [comment]
Will try to release the patch this week.

**Comment by guypaskar** [comment]
Looks good!

**Comment by kay-master** [comment]
I have the same issue even now.. I don't know if it's the way am appending or what but the last few samples are not parsed.

Using FF, 66.0.3 (64-bit) and Chrome, 74.0.3729.169 (Official Build) (64-bit), 

Here is my test code and test video, [Test Code](https://drive.google.com/open?id=1b-FXwodXAFq_hZ347nkpCr5vJyWMF2YW) and [Test Video](https://drive.google.com/open?id=1g1mZy-txKFqUlk4yUNTrQvfB2Je6cCEb), using the latest mp4box release 0.3.20
