### ISSUE TITLE
DEMO TEST DOESN'T WORK ON MY SERVER: Duration of video generated by Media Source Extension using fragmented videos and appendBuffer does not work correctly

### ISSUE THREAD

**Issue by nnalin3** [gpac/mp4box.js#251]
Hello everyone, first of all thanks for this amazing tool, I have an error using the following demo:
https://gpac.github.io/mp4box.js/test/index.html
on the server this works fine, but when I download the files and test it on live server in visual studio code, this does not work correctly, and the length of the video is also not correct, which does not allow me to play the mp4 video.
I have tried with other videos and the same happens, in the demo https://gpac.github.io/mp4box.js/test/index.html it works correctly but on my server it does not work correctly,
apparently the executable or script (mp4box.all.js) in NPM is not updated correctly (https://www.npmjs.com/package/mp4box)

These are the files that I use to do my test:
https://github.com/nnalin3/mp4box_testing_files

  which are the same as found in:
https://github.com/gpac/mp4box.js/tree/master/test

I attach screenshots and console logs files
[demo_mp4box.log](https://github.com/gpac/mp4box.js/files/7522389/demo_mp4box.log)
[my live server.log](https://github.com/gpac/mp4box.js/files/7522390/my.live.server.log)
.

I get this in the demo example
![image](https://user-images.githubusercontent.com/66541640/141346249-28d38b5e-80bf-42a4-a707-11e574f518ae.png)

and on my live server I get different number(you can see, the souce buffer 2 (sound buffer) is empty and the time in source buffer 1 (video buffer) is the same as the demo example but divided by 1000):

![image](https://user-images.githubusercontent.com/66541640/141346559-23151b49-3520-4c7c-8b42-dca3a86ae633.png)

Greetings and thanks in advance

**Comment by ckvv** [comment]
we have same error

**Comment by ckvv** [comment]
> we have same error, the duration is not correct

it is my wrong, video playback time= `duration ` / `timescale `

**Comment by cconcolato** [comment]
I'm not sure I understand the issue. Since it's been a while, I'm not sure the issue still exists. Please reopen the issue if it is still a problem.
