### ISSUE TITLE
cts/pts of the first sample is not 0 

### ISSUE THREAD

**Issue by ziyunfei** [gpac/mp4box.js#253]
![image](https://user-images.githubusercontent.com/1276859/142174895-60660258-591c-4fbd-b1de-43a30ee3867d.png)

ffprobe:

![image](https://user-images.githubusercontent.com/1276859/142173607-3ff7c516-cd5d-43f5-a7c5-8ece911f6b71.png)

https://user-images.githubusercontent.com/1276859/142173870-d47428cf-b548-41bc-b363-ac7404740e49.mp4

**Comment by cconcolato** [comment]
MP4Box.js is returning the Composition Time Stamp (CTS) which for the first frame is not 0. If you want to get the Presentation Time for the first frame, which would be 0, you have to take into account the edit list. 
![image](https://user-images.githubusercontent.com/1830314/159086353-abd318b6-03a5-4c7a-82ad-aeb3d883e9d3.png)
The edit list in your file indicates that the data with CTS < 1024 should not be played. 

Closing this issue as there does not seem to be a bug in mp4box.js. Reopen if you disagree.
