### ISSUE TITLE
AVIF with "mdat" size 0 crashes in MP4box.js

### ISSUE THREAD

**Issue by y-guyon** [gpac/mp4box.js#255]
The attached good.avif is a white 1x1 valid AVIF file. bad.avif is the same one but with a "mdat" size of 0 instead of 33.
They both pass the latest version of the [Compliance Warden](https://github.com/gpac/ComplianceWarden/commit/7554cd1263a86cb281d76d1a8cf23e9e190d414e) but the [web tool](https://gpac.github.io/ComplianceWarden-wasm/avif.html) is not up-to-date.
They both display correctly in Chrome.
They both respect the ISO/IEC 14496-12 - 4.2 specification.

However bad.avif crashes in [MP4box.js](https://gpac.github.io/mp4box.js/test/filereader.html) while good.avif does not.
[good.avif_and_bad.avif.zip](https://github.com/gpac/mp4box.js/files/7581849/good.avif_and_bad.avif.zip)

**Comment by cconcolato** [comment]
Thank you for the report. It should be fixed now.
