### ISSUE TITLE
ref is not defined (ISOFile.prototype.getInfo)

### ISSUE THREAD

**Issue by turbobuilt** [gpac/mp4box.js#262]
Hi, and thanks for a great library.  This makes my job a lot easier!  I found a small bug when parsing an MP4 (mov) file from my phone.  I get the error `ref is not defined` when the function `ISOFile.prototype.getInfo` is running.  I found out how to fix it though, just put `var` in front of the word `ref` and it works.  I have linked to the affected line so that it can be easily found and fixed.  Once again thanks for all the hard work.  I hope this bug report is correct and that I didn't mess it up somehow.  

https://github.com/gpac/mp4box.js/blob/4e1bc23724d2603754971abc00c2bd5aede7be60/src/isofile.js#L337

**Comment by cconcolato** [comment]
Thanks. This has been fixed in https://github.com/gpac/mp4box.js/pull/276.
