### ISSUE TITLE
When playing quicktime videos recorded on iPhone, there's only video, no audio

### ISSUE THREAD

**Issue by tlp** [gpac/mp4box.js#265]
This happens only on Chrome, when using Firefox you get both audio and video.
Audio track is detected as 'mp4a' instead of 'mp4a.40.2', so the SourceBuffer is not initialized at all as it's not supported, however, when hardcoding mp4a.40.2 just for the sake of testing, neither audio nor video works (on Chrome, Firefox works).
Any idea how to make it work?
Thanks!

**Comment by cconcolato** [comment]
Without an example file, it's difficult to help you. Can you share the file that is creating this issue?

**Comment by cconcolato** [comment]
Reopen the issue if the problem still exists and you have a file to share.
