### ISSUE TITLE
Wrong smhd box size when parsing audio muxed by Mp4box.js

### ISSUE THREAD

**Issue by fyuhkust** [gpac/mp4box.js#267]
Hi, I was trying to use Mp4box.js to mux a mp4 encoded by webcodecs. It throws this error on the result mp4 muxed by Mp4box.js:

> [isom] not enough bytes in box smhd: 0 left, reading 4 (file isomedia/box_code_base.c, line 4799)

I will comeup with a PR to fix this problem.

**Comment by fyuhkust** [comment]
here is the PR: https://github.com/gpac/mp4box.js/pull/268

**Comment by cconcolato** [comment]
closed by merging #268
