### ISSUE TITLE
xhr requests are being requested twice for the same range - Why?

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#27]
I noticed in the network session in Chrome that there are requests that simply being requested twice.

after debugging a bit I have seen that in downloader.setCallback there is the line:

var nextStart = mp4box.appendBuffer(response) return with response.usedByets = chunkSize in the first cycle and nextStart is does not change.
Then there is another download of the same segment only response.usedByets = 0.
Only after that nextStart is changed to the next chunk...

Why is that?

**Comment by guypaskar** [comment]
I actually think that this is applicative bug and not an mp4box bug.
I noticed it on the network tab in the developers tool I saw that there are consecutive requests to the same range sometimes.

I could not reproduce now. Will try and let you know.

**Comment by cconcolato** [comment]
Is it still an issue or can we close it?

**Comment by cconcolato** [comment]
Should be fixed with the latest commits. Reopen if this is not the case.
