### ISSUE TITLE
Extract and save single track from MP4?

### ISSUE THREAD

**Issue by ikmolbo** [gpac/mp4box.js#275]
Can MP4Box.js extract and output an audio track from an MP4, as the command line tool can?

`mp4box -single 2 video.mp4 -out audio.m4a`

Thanks.

**Comment by cconcolato** [comment]
Not really.
You could try creating a segmented file (see https://github.com/gpac/mp4box.js#segmentation) from your source file but ignoring the video stream.

**Comment by ikmolbo** [comment]
Understood, thank you for your answer.

**Comment by 1kilogram** [comment]
### @ikmolbo Explain to me, how did you do it? 
 
I can't do it! Neither get the audio, nor remove the video from the mp4 container using segmentation!

**Comment by 1kilogram** [comment]
> Understood, thank you for your answer.

_Please give an example_
