### ISSUE TITLE
sample_delta of the first subsample entry = 0

### ISSUE THREAD

**Issue by podborski** [gpac/mp4box.js#279]
While reviewing an input contribution to MPEG on subsamples I noticed an issue with first sample_delta not being equal to 1.

Try to parse [subs_slice_hvc1.mp4](https://conformance.mpeg.expert/ISOBMFF/published/nalu/hevc/subs_slice_hvc1.mp4) which gives:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/40244254/165211329-d2585d83-d4f0-4b89-9c75-c3699ffc425c.png">

While MP4Box produces:

https://github.com/MPEGGroup/FileFormatConformance/blob/main/file_features/published/nalu/hevc/subs_slice_hvc1_gpac.json

```json
"SubSampleInformationBox": {
                "@Size": "2448",
                "@Type": "subs",
                "@Version": "0",
                "@Flags": "4",
                "@Specification": "p12",
                "@Container": "stbl traf",
                "@EntryCount": "64",
                "SampleEntry": [
                  {
                    "@SampleDelta": "1",
                    "@SubSampleCount": "4",
                 . . .
```

Relevant part from the ISOBMF spec:

> . . . This implies that the sample_delta for the first entry describing the first sample in the track or in the track fragment is always 1.

**Comment by cconcolato** [comment]
When running `MP4Box -diso subs_slice_hvc1.mp4` on the file, MP4Box indicates:
```
[iso file] first entry in SubSample in track SampleTable has sample_delta of 0, should be one. Fixing
```
So I think the file is wrong

**Comment by podborski** [comment]
If this is the case this issue here can probably can be closed and I just opened a related issue in the FileFormatConformance repo to track it there.
