### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#28]
I ran the demo on ff nightly (37.0a1 (2014-12-28)) with the video  - video counter unfragmented.
It seemed to work but it is a bit buggy. 

Will keep testing and update - did anyone else tried to test this?

**Comment by cconcolato** [comment]
Just tried and indeed it's not working as excepted. If you can identify the cause(s), that'd be great. Keep testing on files containing only a single (video) stream and let me know.

**Comment by guypaskar** [comment]
I will give it a shot. That can be also issues with Media Source and not related to the mp4box.

I'll keep updating when I have more info.

**Comment by cconcolato** [comment]
I've just made some tests again with Firefox 37.0a1 (2015-01-08) and it works. It tested with unfragmented versions of: Counter (video only), Counter (with audio and video), BadInfluence (a/v). The other videos not hosted on my server do not work as I don't know how to disable CORS in developer mode (it does not seem possible, see https://bugzilla.mozilla.org/show_bug.cgi?id=1039678). 

Note, I've also tested with IE11 but there are problems (impossible to add properties to ArrayBuffer objects?).

**Comment by guypaskar** [comment]
Tried with counter and BadInfluence and it seems to partly work. Seek (to a not buffered time) did not work, did not start playing again, I did not debug it yet.

Tried it also on Aurora (36) which is moving this week to beta (thus soon moves to release) and it worked. (but same is before no seek to out of 

Also, Tried with big buck bunny (hosted on iwn server with cors enabled) could not even append the init segment correctly.

Also, Firefox does not have activeSourceBuffers.item so it simply gets an error there. (when trying to do realtime download) - FYI

**Comment by guypaskar** [comment]
For the big buck bunny issue I saw on the logs that I get:
"[0:00:13.133]" "[Downloader]" "Received data range: bytes 0-999999/53072113" log.js:27:5
"[0:00:13.172]" "[BoxParser]" "Not enough data in stream to parse the entire "mdat" box" log.js:32:5
"[0:00:13.172]" "[Application]" "Starting to parse movie information" log.js:27:5
"[0:00:13.227]" "[Application]" "Movie information received" log.js:27:5
"[0:00:13.227]" "[Downloader]" "Stopping file download" log.js:27:5
"[0:00:13.228]" "[MP4Box]" "Next buffer to fetch should have a fileStart position of 1000000" log.js:27:5
"[0:00:14.593]" "[MSE - SourceBuffer #1]" "Creation with type 'video/mp4; codecs="avc1.64001f"'" log.js:27:5
"[0:00:15.505]" "[MSE - SourceBuffer #2]" "Creation with type 'video/mp4; codecs="mp4a.40.2"'" log.js:27:5
"[0:00:18.787]" "[MSE - SourceBuffer #1]" "Appending initialization data" log.js:27:5
"[0:00:18.787]" "[MSE - SourceBuffer #2]" "Appending initialization data" log.js:27:5
"[0:00:18.790]" "[MSE - SourceBuffer #1]" "Init segment append ended, updating: false, buffered: (empty), pending: 0" log.js:27:5
"[0:00:18.790]" "[MSE - SourceBuffer #2]" "Init segment append ended, updating: false, buffered: (empty), pending: 0"

**Comment by guypaskar** [comment]
FireFox support stopped working for some reason.

The video is being downloaded and appended but not played. (Tried on the demo app)

**Comment by rbouqueau** [comment]
@cconcolato @guypaskar Do you think it would be relevant to have a liaison with the firefox people? Otherwise I fear they concentrate on a few use-cases (dash.js, etc.) but not on this. Opinion?

**Comment by guypaskar** [comment]
I'll try to talk to them later on tonight. - Can you confirm that it does not work?

It used to work in the past. and there are no errors on the page.

**Comment by guypaskar** [comment]
Any luck here? I don't see any errors, Just the video won't play.

Looks like the buffered array is empty although content was appended without errors

**Comment by guypaskar** [comment]
I have opened a bug in bugzilla - you can register as well and comment to show that this interest others as well.
https://bugzilla.mozilla.org/show_bug.cgi?id=1138992

**Comment by guypaskar** [comment]
video couner does work but when I try on my videos (for example this one http://storage.googleapis.com/peer5_vod/wind2_orig.mp4)  on firefox , it seems like there are no errors but the video would not play.
i.e the video is being downloaded (until completed) but nothing is played.

I tried other videos as well and came up with the same solution.
Can you confirm?

**Comment by cconcolato** [comment]
I confirm the problem. Will check asap.

**Comment by rbouqueau** [comment]
As of Firefox 40, the 'play' button remains grey when providing some content. Firefox nightly (42) doesn't have this issue.
