### ISSUE TITLE
Source is too large

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#29]
I often get both in the demo app and in my own app an error in Datastream.memcpy
"Source is too large"

Did someone else experienced that and knows the reason?

**Comment by guypaskar** [comment]
Will try. At the moment I don't know exact steps.

I think it happens after seek. will try to isolate the issue.

**Comment by guypaskar** [comment]
It looks like this happens when connecting a new data range to an already downloaded data range
i.e

1000-5000 was downloaded and now downloading 550-650, 650-750, 750-850, 850-950,950-1050...

**Comment by guypaskar** [comment]
Did you manage to validate this bug?

**Comment by cconcolato** [comment]
I can't reproduce it. Can you provide the file ? and the exact steps ? Also which browser (and version) are  you using?

**Comment by guypaskar** [comment]
Yes. It does not happen on your demo. But it does on my. Don't understand yet why.

Any ideas on what to look? it always happens when seeking back to an undownloaded part on the point where the new download and the bytes already downloaded intersects. (like the raw example that I gave before)

**Comment by rbouqueau** [comment]
I think these questions still apply ;)

> Can you provide the file ? and the exact steps ? Also which browser (and version) are you using?

Is it possible for you to provide some content?

**Comment by guypaskar** [comment]
@rbouqueau hope you are doing well. 
Testes with Chrome on mac (Version 40.0.2214.94 (64-bit)) File is big buck bunny

I have setup a server with an example to when it happens - file and all.

Sent the address and instruction of how to reproduce via Email to Cyril (private server and don't want to publish it here).

**Comment by guypaskar** [comment]
Solved here https://github.com/gpac/mp4box.js/commit/c5d90f3c9687f67d41773fedb3f64f7ee234d287
