### ISSUE TITLE
newLength can be negative in some scenarios 

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#31]
And the line smallB = new Uint8Array(newLength); gets an error (mp4Box line 216)

for example for these parametes I get it

b.byteLength = 300001
b.fileEnd = 24298968
b.fileStart = 23998968

ab.bytesLength = 39935
ab.fileEnd = 24157404
ab.fileStart = 24117470

offset = 181499 --> newLength = -141564 --> error

**Comment by cconcolato** [comment]
Indeed, a bug I thought I had caught all of these in the unit tests ... Thanks for reporting. Should be fixed now. Let me know if you still have an issue otherwise please close the issue.

**Comment by guypaskar** [comment]
Looks good now.
