### ISSUE TITLE
Error loading/playing unfragmented MP4 in demo-player

### ISSUE THREAD

**Issue by Gundeck** [gpac/mp4box.js#315]
First of all, thank you for the mp4boxjs project !

I used the demo player local on my PC. When I try to load an unfragmented, larger MP4 file, Firefox and Chrome produce the following errors:

Firefox 110.0:
Uncaught DOMException: The quota has been exceeded.

Chrome 110.0.5481.178:
Uncaught DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

I suspect that the memory is overflowing from the browser. Is there a solution to the problem ?

Good work and thanks !

**Comment by hughfenghen** [comment]
Try calling `releaseUsedSamples`

![image](https://user-images.githubusercontent.com/3307051/235358978-1afbdd34-6130-480b-8ee6-c7c4142e5d95.png)
https://gpac.github.io/mp4box.js/#appendbufferdata
