### ISSUE TITLE
When downloading the last couple of chunks and seek back I always get the same nextParsePosition

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#32]
consider the following scenario

1) seek to the middle of the video
2) seek to the end of the video (the last chunk is downloaded)
3) seek to the middle of the video again

result - the nextParsePosition returns from append is always the end of the file even though I have appended the middle of the video.

**Comment by guypaskar** [comment]
Here is another strange but similar issue

1) seek to middle of video, say downloaded a range of 500-1000
2) seek to 3/4 of the video - say downloaded range 2000-2500
3) seek back and download 450-550 - no when I append this data the append function return 1000 as the nextParsePosition but no onSegement happens and there is nothing to play.

**Comment by cconcolato** [comment]
I confirm the bug. I will fix it but this might take some time.

**Comment by guypaskar** [comment]
Complex bug or just no time?

**Comment by cconcolato** [comment]
Just no time. Should have more in the coming days.

**Comment by guypaskar** [comment]
Cool. Thanks.

**Comment by cconcolato** [comment]
The latest batch of commits should fix this problem. Please confirm and close the issue if resolved.
