### ISSUE TITLE
Where the Are the Actual Media Files Used in Testing?

### ISSUE THREAD

**Issue by seflless** [gpac/mp4box.js#333]
Where are the test audio/video files located?

I see mention of a lot of `ff-conformance/*` media files in tests, but there are no media files in the repo. When cloning and running locally `grunt test`, no tests seem to run or files get downloaded.

**Comment by cconcolato** [comment]
Sorry for the confusion. I should clean that. I have not committed the files in the repository because they are hosted elsewhere, officially https://standards.iso.org/iso-iec/14496/-32/ed-1/en/conformance/.
