### ISSUE TITLE
[QUESTION] onSamples, sample output object description

### ISSUE THREAD

**Issue by Pensarfeo** [gpac/mp4box.js#379]
Hi, would it be possible to get a description of the sample's object in the samples output array from "onSamples"?
Or at least a reference where that information could be found?

Thanks!! :)

**Comment by DenizUgur** [comment]
You can have an idea from this location. Until we change to typescript or declaration of types (.d.ts), inspecting the source code is your best option.

https://github.com/gpac/mp4box.js/blob/57463b4e41cfeb9434bf59c698485de8b99e69eb/src/isofile-sample-processing.js#L401

**Comment by Pensarfeo** [comment]
thanks
