### ISSUE TITLE
if the chunkSize config is set to a small value, then for some mp4 video, fragmentation takes a lot of time.

### ISSUE THREAD

**Issue by ashuvssut** [gpac/mp4box.js#391]
When using a download chunk size ranging between 1 MB to 3 MB, as demonstrated in the attached video below, I've noticed a significant delay in the completion of mp4box fragmentation for many MP4 videos with durations less than 1.5 minutes. Please refer to the linked video for illustration. Increasing the chunk size appears to mitigate this delay in fragmentation initiation.

Interestingly, for videos with durations exceeding 1.5 minutes, a chunk size of 1 MB performs adequately. However, I'm puzzled as to why videos with durations less than 1.5 minutes necessitate a larger chunk size to mitigate this delay.

> I mention the 1.5-minute threshold because, irrespective of their size, videos consistently experience prolonged start-up times. (1.5 minutes serves as an average approx duration).

[output_compressed.webm](https://github.com/gpac/mp4box.js/assets/60546840/8e721e28-2e21-436f-b753-25f1b23a30bb)

In the demo video provided above:

1. Initially, a 3-minute duration video was used, where setting the `chunkSize` to 1MB resulted in expected behaviour: i.e video started without any delay.

2. However, when a video with a duration of less than 1 minute was used, setting the `chunkSize` to 1MB resulted in significant start-up delay. Increasing the `chunkSize` to 4MB improved the video start time.
    - This same behaviour was also tested with a less than 1-minute [4K MP4 video of 180MB](https://drive.google.com/file/d/1u11TBV-Ei_YJmx9-BsvNP2UC2TaVdpJ-/view?usp=drive_link) in size.
    - It's notable that a very large `chunkSize` is required to initiate the video slightly earlier. Setting `chunkSize` to 1MB results in considerable delay in video start-up.

> EDIT: i did a few more tests on 2 more files
>
>>The 1.25GB mp4 file is of 15mins: https://drive.google.com/file/d/1GI2pFTCpTcyu-hQt89AQpe-pDBiA6uPL/view?usp=drive_link
>>The 130MB 3gp file is of 30secs:  https://drive.google.com/file/d/1bLyuIn3AjxcQ5_EYppTCej7ASt0QMlzp/view?usp=drive_link
>
> Regarding the 2nd point mentioned above, it's not limited to files of duration  1-min 4K video . A more accurate description would be: "mp4box struggles with fragmentation particularly when dealing with files that have a disproportionately large size relative to their short video duration."
 
    
### Steps to set up the mp4box player playground locally shown in the video

clone [this repo](https://github.com/stacknide/mp4box-apps)
```bash
yarn install
yarn dev # starts demo-player app
yarn serve # starts the media sever
yarn dev:player # (Optional) re-build mp4box-player lib by watching for changes
```

**Comment by PopeyeSailorMike** [comment]
Hi. I just had a look at this and it got me wondering why your building an mp4 blox player and not simply customizing video.js

**Comment by PopeyeSailorMike** [comment]
Thanks for the detailed breakdown. Check this out. This uses Mp4Box to append fragmented mp4.

**Comment by PopeyeSailorMike** [comment]
Managed to update the repo above. It's working and it appears it will be possible to achieve the same results as your mp4box player by using this plugin which preceded vhs(videojs-http-streaming utilizing MSE under the hood for DASH and HLS): https://github.com/videojs/videojs-contrib-media-sources/blob/master/index.html

**Comment by ashuvssut** [comment]
Were you able to do seek Operation too on that flv video?

**Comment by PopeyeSailorMike** [comment]
I've built it but the sample FLV is only 6 seconds long. It should work just fine with longer videos.

**Comment by PopeyeSailorMike** [comment]
So, I tried longer videos and it appears that flv.js doesn't seek as of right now and sourceBuffer requires the exact codecs for raw byte ranges to work with MSE. Video.js is great because it allows you to specify the techOrder and toggle them on/off as needed. That's why I suggested it but Mp4box appears to have a consistent method for handling raw video byte ranges.

**Comment by ashuvssut** [comment]
We observed that having a smaller value in `Segment Size` field (i.e `nb_samples` or number of frames in a segment) helped fixed the issue with those high resolution mp4 file.

So in the linked PR above, we made corrections to calculate `nb_samples` and `chunkSize` precisely based on a constant variable `SEGMENT_DURATION_SECS`

**Comment by PopeyeSailorMike** [comment]
Cool!
