### ISSUE TITLE
Too much memory for large files

### ISSUE THREAD

**Issue by tiuvi** [gpac/mp4box.js#393]
Library uses too much memory for large files

![image](https://github.com/gpac/mp4box.js/assets/69035383/15a630f8-cb4d-4b22-a194-d4efab6b5867)

In this case the file weighs 500 MB and uses 700 MB, I think the memory could be lowered to 0 using this api.

https://developer.mozilla.org/en-US/docs/Web/API/File_System_API

This api lets you create a virtual file where you can save the data and then obtain it through the demux by reading the file.

I have already made progress in demux webm, ffmpeg and webCodecs by reducing memory.
I would only be missing the mp4 demuxer.

I don't know exactly where the memory expenditure is, it could be when reading the file that everything is stored in memory and then reading it to process it or it could be when creating the chunks that it stores them in memory and that is why it uses so much memory.

In either case you could use this api to read directly from the file.

![image](https://github.com/gpac/mp4box.js/assets/69035383/a943d665-ab1d-4a57-a432-e3ffc52f79ab)

If you use it, I recommend using this one, which is compatible with webview
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle

![image](https://github.com/gpac/mp4box.js/assets/69035383/ebb43cdb-cc09-47d5-862e-0f23e5b21546)

You only need to save the file's offsets and then read them.

Someone who knows the library well could implement it quickly, greetings.

**Comment by rbouqueau** [comment]
Hi there, I think you'll have more chance if you write in English. Thanks

**Comment by DenizUgur** [comment]
MP4Box.js has `releaseUsedSamples(id, sampleNumber)` function to release the memory once you are done with the samples. You shouldn't need to hold all samples in the memory.

Although I agree with the OPFS suggestion. We've used OPFS to increase performance and maximum file size allowence when using gpac with WebAssembly. There could be a future where we use it inside MP4Box.js as well.

**Comment by hughfenghen** [comment]
![image](https://github.com/user-attachments/assets/fbfe7707-e83a-4c2f-8634-5f9552f04292)

Theoretically, providing only the raw data of the `moov` box (without the `mdat` box) would make it possible to obtain all Sample objects (without the `data` field). I could then use the OPFS API to read `data` based on the `offset` and `size` objects as needed.  
This strategy can avoid the unnecessary resource waste of fetching large amounts of data (from the mdat box) at the initial stage only to discard it immediately (via releaseUsedSamples).

It would be great if mp4box.js could support this feature; otherwise, I'll need to manually parse the ctts and stsz boxes.

---

A typical use case would be implementing video editing functionality, where quick parsing of the video file is needed at the initial stage to provide keyframe thumbnails without requiring the `data` field for all Sample objects.

**Comment by DenizUgur** [comment]
MP4Box.js also parses `ctts` and `stsz` boxes. I haven't verified the implementation yet but you can access those boxes on `onMoovReady`. Then you can use the FileSystem APIs mentioned by @tiuvi to read the file as you wish.

Just note that, in order to use sync APIs, you have to use them in a Web Worker.

Supporting OPFS and more optimized file I/O is definitely something to be done for this library. There's no immediate plan to do it though.

**Comment by hughfenghen** [comment]
@DenizUgur Thank you for your patience in responding.  

Is it possible for `mp4box.js` to provide all 'lightweight Sample objects' (containing the `offset`, `size`, `cts`, `dts`, and `is_sync` without `data` fields) after parsing the `moov` box (for instance, via `onReady`)?   
In some scenarios, only a small amount of data (the `moov` box) is needed, rather than the entire video file.

File reading operations are recommended to be handled externally rather than within `mp4box.js`.  

_P.S. I’ve open-sourced a [small library](https://github.com/hughfenghen/opfs-tools) based on the OPFS API, which makes it very easy to read and write files directly in the browser._

**Comment by DenizUgur** [comment]
I think it's doable. Would you like to open a PR for it? I'll be happy to review it.

**Comment by hughfenghen** [comment]
OK, if I implement this feature in the future, I will submit a PR to mp4box.js.

**Comment by hughfenghen** [comment]
Wow, that's awesome!  Thank you for the information.

**Comment by tiuvi** [comment]
I'm giving you an example of what I'm doing in case it could help you implement the function. Currently the library saves the entire file in memory. I also had a double file in memory when using the copied samples, which I was able to solve by deleting the copy, but even so I think the best thing to do would be:
1. Read the file, get metadata and the beginning and end of the frames, but without saving the frame.
2. An additional reading function to read the frame directly from the file, already knowing when the frame will start and end.
I know it's quite a bit of additional time, but hey, webcodecs is already working. Decoder support is missing.


My current function

```
 const getVideoFramesMp4 = globalThis[nameGlobal]['getVideoFramesMp4'] = async function (args) {

        const { urlBlob } = args;

        //return value
        const videoOption = {
            config: null,
            lenChunk: 0,
            getVideoChunk: () => {

            },
            chunks: [],
            err: null,
        };

        return (await new Promise(async (resolve) => {

            let file = null;

            file = MP4Box.createFile();

            //Generando los errores
            file.onError = (error) => {
                resolve(error);
            }

            //Cuando el archivo se carga
            file.onReady = function (info) {

                //Obteniendo la informacion
                const track = info.videoTracks[0];
                
                videoOption.config = {

                    codec: track.codec.startsWith('vp08') ? 'vp8' : track.codec,
                    codedHeight: track.video.height,
                    codedWidth: track.video.width,
                    description: ((track) => {

                        const trak = file.getTrackById(track.id);

                        for (const entry of trak.mdia.minf.stbl.stsd.entries) {

                            const box = entry.avcC || entry.hvcC || entry.vpcC || entry.av1C;

                            if (box) {
                                const stream = new DataStream(undefined, 0, DataStream.BIG_ENDIAN);
                                box.write(stream);
                                return new Uint8Array(stream.buffer, 8);  // Remove the box header.
                            }

                        }

                        resolve({ err: "avcC, hvcC, vpcC, or av1C box not found" })

                    })(track),

                };


                const trackAudio = info.audioTracks[0];
                videoOption.audioConfig = {

                    codec: trackAudio.codec,
                    sampleRate: trackAudio.audio.sample_rate,
                    numberOfChannels: trackAudio.audio.channel_count,
                    description: (() => {

                        const trak = file.getTrackById(trackAudio.id);
                        for (const entry of trak.mdia.minf.stbl.stsd.entries) {

                            if (!entry?.esds?.esd?.descs[0]) return (undefined);

                            // 0x04 is the DecoderConfigDescrTag. Assuming MP4Box always puts this at position 0.
                            //if (entry.esds.esd.descs[0].tag == 0x04) return (undefined);
                            // 0x40 is the Audio OTI, per table 5 of ISO 14496-1
                            //if (entry.esds.esd.descs[0].oti == 0x40) return (undefined);
                            // 0x05 is the DecSpecificInfoTag
                            //if (entry.esds.esd.descs[0].descs[0].tag == 0x05) return (undefined);

                            return entry.esds.esd.descs[0].descs[0].data;
                        }
                        /*
                                                // TODO: make sure this is coming from the right track.
                                        
                                                // 0x04 is the DecoderConfigDescrTag. Assuming MP4Box always puts this at position 0.
                                                console.assert(file.moov.traks[1].mdia.minf.stbl.stsd.entries[0].esds.esd.descs[0].tag == 0x04);
                                                // 0x40 is the Audio OTI, per table 5 of ISO 14496-1
                                                console.assert(file.moov.traks[1].mdia.minf.stbl.stsd.entries[0].esds.esd.descs[0].oti == 0x40);
                                                // 0x05 is the DecSpecificInfoTag
                                                console.assert(file.moov.traks[1].mdia.minf.stbl.stsd.entries[0].esds.esd.descs[0].descs[0].tag == 0x05);
                        
                                                return file.moov.traks[1].mdia.minf.stbl.stsd.entries[0].esds.esd.descs[0].descs[0].data;
                        */

                    })(),

                };

                videoOption.lenChunk = info.tracks[0].nb_samples;

                videoOption.getVideoChunk = (index) => {

                    if (index === info.tracks[0].nb_samples) {
                        return ({ err: "No hay mas muestras por leer" })
                    }

                    const sample = file.getTrackSample(info.tracks[0].id, index);
                    return (new EncodedVideoChunk({
                        type: sample.is_sync ? "key" : "delta",
                        timestamp: 1e6 * sample.cts / sample.timescale,
                        duration: 1e6 * sample.duration / sample.timescale,
                        data: sample.data
                    }));
                }

                videoOption.lenChunkAudio = info.tracks[1].nb_samples;

                videoOption.getAudioChunk = (index) => {

                    if (index === info.tracks[1].nb_samples) {
                        return ({ err: "No hay mas muestras por leer" })
                    }

                    const sample = file.getTrackSample(info.tracks[1].id, index);

                    const audioChunk = {
                        type: sample.is_sync ? "key" : "delta",
                        timestamp: 1e6 * sample.cts / sample.timescale,
                        duration: 1e6 * sample.duration / sample.timescale,
                        data: sample.data
                    }

                    return (new EncodedAudioChunk(audioChunk));

                }

            }
```


The solution would be that my getVideoChunk and getAudioChunk functions would get the data from the file and not from memory.


Also, a good solution would be that the file.getTrackSample function had an additional getSampleData() method that would only be called when the getVideoChunk or getAudioChunk functions were called. I know it's a lot of work, but it would be great.
