### ISSUE TITLE
Detect if faststart is enabled for a streamed video file?

### ISSUE THREAD

**Issue by raedle** [gpac/mp4box.js#395]
Is there a way to detect if `faststart` was enabled when using ReadableStream through fetch API's `response.body`?

The goal would be to read only a few bytes of the fetch API body and then either continue reading or abort depending on whether `faststart` was enabled (or if the `MOOV` box was found).

**Comment by DenizUgur** [comment]
You could use [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to abort a `fetch` request. You have to wait for an `onReady` callback from this library or until a download threshold you defined. I'm assuming you are using a [`TransformStream`](https://developer.mozilla.org/en-US/docs/Web/API/TransformStream) or similar to parse incoming data
