### ISSUE TITLE
[Object Object] in avcC: SPS and PPS

### ISSUE THREAD

**Issue by manosriram** [gpac/mp4box.js#399]
![Screenshot 2024-05-18 at 2 53 50 AM](https://github.com/gpac/mp4box.js/assets/38112857/b534cbb9-ff57-4e77-b15a-68ea12e7e091)

**Comment by paulhiggs** [comment]
The SPS and PPS elements are constructed as an array of objects where the object contains a length and an array of values.

I can fix this bug, but it would he helpful if you can share your 'video.mp4' file so I can text the fix before creating a PR for it.

**Comment by paulhiggs** [comment]
Results from PR #412
![image](https://github.com/user-attachments/assets/8b844fdf-a8b6-494f-93dc-41b456aaf148)

![image](https://github.com/user-attachments/assets/c7b0b6b7-1fd1-4d80-b466-b981bad67d41)
