### ISSUE TITLE
jitter when seek

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#41]
Happens the videos in the demo page.
When seeking to a downloaded range and also to an undownloaded range.

I don't remember it was always so jittery...

**Comment by cconcolato** [comment]
At some point, it noticed some jitter. It was a bug introduced earlier but fixed since then I think in eee9669dc513f272f619e5ef7bcd39bdf062871e. Can you confirm and close?

**Comment by guypaskar** [comment]
Still very jittery on seek.

Even to an already downloaded part.

**Comment by cconcolato** [comment]
Apparently the problem only occurs on Chrome on OS X, as reported in #45

**Comment by cconcolato** [comment]
Seems fixed. Open a new issue if this is still the case.
