### ISSUE TITLE
it can resolve flv format video?

### ISSUE THREAD

**Issue by jackluoluo** [gpac/mp4box.js#418]
only can resolve MP4+avc? 
or MP4+hevc?
tks

**Comment by rbouqueau** [comment]
The community added VP8, VP9, VVC, there's a PR for [AVS3](https://github.com/gpac/mp4box.js/pull/408), ...

If you need support for the 'flv' container you could also elaborate on that. Another option would be to leverage the gpac wasm build.

What are you trying to achieve?

**Comment by jackluoluo** [comment]
i want to extract audio buffer from flv format video,like using mp4box.js to extract in the browser.
now i using mp4box.js to handle flv video, return nothing.
tks.

**Comment by rbouqueau** [comment]
mp4box.js doesn't support flv at the moment. There was a related discussion in #391 in case it helps you.

**Comment by jackluoluo** [comment]
OK thank you
发自我的 iPhone

在 2024年11月7日，17:26，Romain Bouqueau ***@***.***> 写道：

﻿

mp4box.js doesn't support flv at the moment. There was a related discussion in #391<https://github.com/gpac/mp4box.js/issues/391> in case it helps you.
