### ISSUE TITLE
how to save the data that by mp4box parsed?

### ISSUE THREAD

**Issue by jackluoluo** [gpac/mp4box.js#422]
my useage sence as fllow

video buffer from MediaRecorder
audio buffer from mp4box.js parse mp4 video

1.use mp4box.js appendBuffer
2.use flush get merged buffer --here is undefined 

```
mergeArrayBuffer(a_ab, v_ab, cb) {
  const mp4File = MP4Box.createFile();

 
  mp4File.onReady = (info) => {
      console.log(info);// has audio track and video track
      const mergedBuffer = mp4File.flush(); //!important mergedBuffer is undefined
      if (mergedBuffer) {
          const blob = new Blob([mergedBuffer], { type: "video/mp4" });
          const url = URL.createObjectURL(blob);
          cb(url);
      } else {
          console.error("merge error");
      }
   mp4File.start();
  };


  this.appendBufferInChunks(mp4File, v_ab, 0); 
  this.appendBufferInChunks(mp4File, a_ab, v_ab.byteLength); 
}

appendBufferInChunks(mp4File, buffer, fileStart) {
  const chunkSize = 64 * 1024; 
  let offset = 0;
  while (offset < buffer.byteLength) {
      const chunk = buffer.slice(offset, offset + chunkSize);
      chunk.fileStart = fileStart + offset;
      mp4File.appendBuffer(chunk);
      offset += chunkSize;
  }
}

```

can you help me check it?
tks

**Comment by DenizUgur** [comment]
Hi, `.flush()` does not return anything. So, you won't get the buffers that way. See if `mp4File.stream.buffers` can help you. The description for `ISOFile.stream.buffers` property is:

>List of ArrayBuffers, with a fileStart property, sorted in fileStart order and non overlapping

**Comment by jackluoluo** [comment]
use mp4File.stream.buffers got the data, but no audio.
but above i use mp4File.appendBuffer(chunk);//audio 

Can you tell me roughly what the problem is?
tks

**Comment by DenizUgur** [comment]
Could you give a bit more information on what you're trying to achieve?

**Comment by jackluoluo** [comment]
I want to use mp4box.js to merge audio data and video data and then download the full video

**Comment by DenizUgur** [comment]
I assume `a_ab` and `v_ab` are entire audio or video files, presumably in MP4 container? Is that correct?

**Comment by DenizUgur** [comment]
Okay, what your code is doing is concatenating video and audio files. That won't work for MP4 files. You can verify this by playing the "merged" file at the offset of `v_ab`; you will only be playing audio now.

What you need to do is multiplex video and audio. You can do this by creating a new file, adding both video and audio tracks, and adding samples to each track.

See the [isofile-advanced-creation.js](https://github.com/gpac/mp4box.js/blob/master/src/isofile-advanced-creation.js) file for the relevant methods. You can extract the samples from your video and audio files using [`setExtractionOptions(track_id, user, options)`](https://github.com/gpac/mp4box.js?tab=readme-ov-file#setextractionoptionstrack_id-user-options) and retrieve the samples with [`onSamples(id, user, samples)`](https://github.com/gpac/mp4box.js?tab=readme-ov-file#onsamplesid-user-samples).

We don't have detailed documentation besides the source code and some tests.

**Comment by DenizUgur** [comment]
Based on the information you gave me, yes.

**Comment by jackluoluo** [comment]
hello, What format is the audio data obtained in this way？
```
 this.mp4BoxFile.setExtractionOptions(this.audioTrack.id);
    let audioChunks = [];
    this.mp4BoxFile.onSamples = (id, user, samples) => {
      samples.forEach((sample) => audioChunks.push(sample.data));
    };
    this.mp4BoxFile.start();
    console.log(audioChunks);
    this.audio_C = this._mergeArrayBuffers(audioChunks);
    console.log(this.audio_C);
```
![image](https://github.com/user-attachments/assets/82902ba2-6594-49cb-a822-82fcbd527182)
