### ISSUE TITLE
Sample CTS is calculated incorrectly

### ISSUE THREAD

**Issue by amirlivneh** [gpac/mp4box.js#46]
The CTS of samples seem to calculated incorrectly. I've had this problem with every MP4 I've tried.

I'm mostly interested in sample.cts-sample.dts for any given sample, and interestingly, it looks like I can get the correct value for sample i by doing samples[i+1].cts - samples[i+1].dts.

For the same video track, these are the first samples reported by mp4box.js:
Sample 1	DTS 0	CTS 7507
Sample 2	DTS 3753	CTS 11260
Sample 3	DTS 7507	CTS 22522
Sample 4	DTS 11260	CTS 18767
Sample 5	DTS 15014	CTS 15014
Sample 6	DTS 18768	CTS 33783
Sample 7	DTS 22522	CTS 30029
Sample 8	DTS 26275	CTS 26275

and these are the samples reported by doing MP4Box -dts:
Sample 1	DTS 0	CTS 7507
Sample 2	DTS 3753	CTS 18768
Sample 3	DTS 7507	CTS 15014
Sample 4	DTS 11260	CTS 11260
Sample 5	DTS 15014	CTS 30029
Sample 6	DTS 18768	CTS 26275
Sample 7	DTS 22522	CTS 22522
Sample 8	DTS 26275	CTS 33783

**Comment by cconcolato** [comment]
Thanks for the report. The CTS computation, in particular with B frames or edit lists, hasn't been thoroughly tested. I'll try to fix it but it would help if you had a simple file to test.

**Comment by cconcolato** [comment]
Should be fixed. Please check with your file and close the issue or let me know.

**Comment by amirlivneh** [comment]
The issue is fixed. Thank you.
