### ISSUE TITLE
"would be nice to have something like inputIsoFile.getBox(type)/getBoxes(type)"

### ISSUE THREAD

**Issue by rbouqueau** [gpac/mp4box.js#50]
Request by @KozhinM at https://groups.google.com/forum/#!topic/dashjs/5PmEkjKILDQ

**Comment by tieleman** [comment]
See PR #51.

**Comment by rbouqueau** [comment]
Thank you, that's very appreciated :)

**Comment by KozhinM** [comment]
@tieleman, @rbouqueau, thanks for this feature. Really handy methods!
