### ISSUE TITLE
Cannot read property type of undefined

### ISSUE THREAD

**Issue by FranklinWaller** [gpac/mp4box.js#55]
So i'm trying to appendBuffer a mp4 array buffer but the box is undefined at box-parser.js line 37. The video plays inside the browser and on Windows 8.1's video player.

Here's the video we used:
https://mega.co.nz/#!3RdyjK7R!uuG7lHDrDQDcuY5YoqkRuI9HVaJBSzLWEgqVyqqJQxc

And a snippet of code we used:

```javascript
var file = response.response;
file.fileStart = 0;
mp4Box.appendBuffer(file);
```

**Comment by cconcolato** [comment]
Thanks for the report. Your file is an invalid ISOBMFF. I made mp4box.js more robust to those and pushed on master and dev branches. This should fix your problem.

**Comment by FranklinWaller** [comment]
Thanks for the quick response. Sadly this didn't fix the issue. The error 'Invalid typed array length' comes up now. (DataStream.js line 186) The length returns -7.

**Comment by cconcolato** [comment]
Ok this is a known bug. The dev branch has a fix for it. You can try it here:
http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/dev/
Unfortunately, your file has another error (negative stts). I've fixed it but that's not sufficient there is another error. Out of curiousity, do you know how that file was generated?

**Comment by FranklinWaller** [comment]
Tested it and it doesn't throw any errors. But the onReady callback is not called i guess that has to do with the errors in the file itself? The file is generated using a mpegts project
You can find the mapping of the file here https://github.com/RReverser/mpegts/blob/gh-pages/mpegts_to_mp4/index.js at line 170

**Comment by FranklinWaller** [comment]
Tested it and it doesn't throw any errors. But the onReady callback is not called i guess that has to do with the errors in the file itself? 
The file is generated using RReverser's mpegts project (https://github.com/RReverser/mpegts/)
You can find the mapping of the file here https://github.com/RReverser/mpegts/blob/gh-pages/mpegts_to_mp4/index.js at line 170

We made a dump with mp4box on mac : http://pastebin.com/3C4MmNaW
