### ISSUE TITLE
Uncaught TypeError: box.parse is not a function

### ISSUE THREAD

**Issue by tghosgor** [gpac/mp4box.js#56]
Here is the call path:

```
BoxParser.parseOneBox @ box.js:196
ISOFile.parse @ isofile.js:92
MP4Box.appendBuffer @ mp4box.js:366
```

This only happens when I call `appendBuffer` with the buffer that have 0 offset in file. After that, all `appendBuffer` calls start the give this error.

But if I push buffers with non-zero offset before pushing the buffer with zero offset, they don't cause errors. Still, pushing the zero offset buffer starts the problem again. What am I doing wrong?

P.S. I'm using Chromium 43. I include the scripts before the script that use MP4Box.

The MP4 file has this layout:
ftyp          0 32
moov         32 2189359
    2189391 0

This is the range I'm pushing when errors start: offset: 0, ArrayBuffer.byteLength: 524288

**Comment by tghosgor** [comment]
Ah I noticed there is also a box-parse.js. It is not mentioned at the end of README.md. My bad.

**Comment by rbouqueau** [comment]
Is it possible to propose a pull request regarding README.md? Thanks

**Comment by cconcolato** [comment]
I've just updated the README. The preferred method to include mp4box.js in your web page is to use the grunt-generated singe-file. You should not have to include manually each file. HTH.

**Comment by tghosgor** [comment]
Thanks.
