### ISSUE TITLE
Uncaught RangeError: Invalid typed array length

### ISSUE THREAD

**Issue by tghosgor** [gpac/mp4box.js#57]
This error is raised while using appendBuffer.

This is the call path:
```
DataStream.mapUint8Array @ DataStream.js:186
DataStream.readString @ DataStream.js:613
BoxParser.url Box.parse @ box-parse.js:789
BoxParser.parseOneBox @ box.js:196
BoxParser.drefBox.parse @ box-parse.js:777
BoxParser.parseOneBox @ box.js:196
BoxParser.ContainerBox.parse @ box-parse.js:25
BoxParser.parseOneBox @ box.js:196
BoxParser.ContainerBox.parse @ box-parse.js:25
BoxParser.parseOneBox @ box.js:196
BoxParser.ContainerBox.parse @ box-parse.js:25
BoxParser.parseOneBox @ box.js:196
BoxParser.ContainerBox.parse @ box-parse.js:25
BoxParser.parseOneBox @ box.js:196
BoxParser.ContainerBox.parse @ box-parse.js:25
BoxParser.parseOneBox @ box.js:196
ISOFile.parse @ isofile.js:92
MP4Box.appendBuffer @ mp4box.js:366
```

The length that causes the error is `-8`. It goes on like `13` `4` `4` ... `-8`.

The error starts with the last push and keeps going:
```
arrayBuffer.fileStart: 0, arrayBuffer.byteLength: 524288
...
arrayBuffer.fileStart: 1572864, arrayBuffer.byteLength: 524288
arrayBuffer.fileStart: 2097152, arrayBuffer.byteLength: 524288
```

**Comment by tghosgor** [comment]
Apparently I need to use a typed `Uint8Array` array instead of an `ArrayBuffer`. Calling the name `ArrayBuffer` in README.md is confusing.

**Comment by rbouqueau** [comment]
Is it possible too to propose a pull request regarding README.md? Thanks

**Comment by cconcolato** [comment]
I'm not sure the problem comes from you using ArrayBuffer, because it's heavily used in the unit testing. For instance, that's what XHR calls typically return. Additionally, mp4box.js uses DataStream.js which supports ArrayBuffer or any Typed Array. 

The negative value for the buffer length seems to be the problem, possibly due to an error in the parsing of the "url" Box. Can you try with the dev branch, in particular with that fix 77a4a974abbf265118d189b0f68fb9da33843c41? or provide your test file ?

**Comment by tghosgor** [comment]
That commit is also merged to master. Nevertheless I have tried the dev branch and it seems to work fine, I mean at least no errors occur. Even onReady is fired (it wasn't fired when using typed arrays on master branch).

I guess there is no need to bisect or something since no actual version exists to backport.

However, when last part of the video file is appended, there is a 5 seconds high (100% of a core) CPU usage on chrome process and the memory usage of that tab doubles (364MB -> 800~MB -> 364MB for a 76MB video file) for the duration of the CPU spike. I am using HTML5 FS api to read the file in in blocks in a for loop so probably it is the CPU usage of that operation. If I try with a 350~MB video file it randomly has 15~ or so errors and chrome tab crashes so I guess it's something about not being able to allocate memory. Anyway, apparently I should append 2 segments at a time.

The real problem on #dev is that `onSegment` is not called. I get the `onReady` event, two tracks are detected.

This block of code is called from inside `onReady` handler:

```javascript
this.mp4box.onSegment = this.mp4boxSegment.bind(this);

tracks.forEach(function(t) {
  if (t.audio || t.video) {
    var mimeType = (t.audio ? 'audio' : 'video');
    this.sourceBuffers[track.id] = this.mediaSource.addSourceBuffer(mimeType + '/mp4 ; codecs=' + t.codec);
    this.mp4box.setSegmentOptions(t.id, this.sourceBuffers[t.id], {});
  } else {
    console.error('Unknown track type:', t);
  }
}.bind(this));

var iSegs = this.mp4box.initializeSegmentation();

console.log('init segments', iSegs);

iSegs.forEach(function(iSeg) {
  var sb = iSeg.user;
  sb.appendBuffer(iSeg.buffer);
});
```

**Comment by cconcolato** [comment]
For the problem related to segments not being triggered, the dev branch requires calling ```mp4box.seek(0, true)``` when you want the extraction to start. I will document it, sorry for the problem. Can you give it a try?

**Comment by tghosgor** [comment]
Modified the code above but still there is no segmentation.

```
var iSegs = this.mp4box.initializeSegmentation();

console.log('initialize segmentation', iSegs);

iSegs.forEach(function(iSeg) {
  var sb = iSeg.user;
  sb.appendBuffer(iSeg.buffer);
});

console.log('seeking to 0');
this.mp4box.seek(0, true);
```

**Comment by tghosgor** [comment]
As far as I see the only place `onSegment` is called is `MP4Box.processSamples` and the `if (!this.sampleProcessingStarted) return;` seems to always return for me.

**Comment by cconcolato** [comment]
Thanks. Indeed, the ```seek``` method tells MP4Box where to start extracting/fragmenting from while ```start``` tells it to actually start.
