### ISSUE TITLE
seeking results in artifacts

### ISSUE THREAD

**Issue by Pablo76** [gpac/mp4box.js#64]
I segment an mp4 (h264+aac) movie using mp4box.js and feed it into video tag. The problem is that after I seek I get artifacts for a few seconds. I'm not that experienced in MSE and web/html5/javascript (but I'm ok with h264/mp4 themselves) so, maybe mp4box.js is missing more explanation how to do seeking properly?

I tried to debug and it seems that mp4box.js produces good result with minor issues, but even when I fixed these minor issues I still cannot get seeking working without artifacts.

In my case I seek to pos=160sec. mp4box.seek(pos, true) returns correct offsets of the first i-frame that comes before 160sec. In my case, seeked i-frame is at 156sec. I verified that seeking part works properly: I extracted raw bitstream from output generated by mp4box and the bitstream "skips" to the requested i-frame as expected. However, I see this in browser: when i seek after enough data got prebuffered playback starts and player shows static picture of the _next_ i-frame which is located at 166sec. Picture stays static for a few seconds until playback reaches 166sec and it resumes at this point. No matter what I try, I cannot make player start playback from that i-frame that I seeked to (located at pos=156sec).
Minor issues that I fixed but it didn't help to solve the issue: all moof fragments don't have i-frame flags set for i-frames. I added that code in createSingleSampleMoof:
trun.sample_flags[0] = sample.is_rap ? (2 << 4) : 0;

Also, if I simply save generated fragmented movie as an mp4 file and try to play it with vlc/media player I get similar artifacts when i seek in these movies.

Note that this paused next i-frame vs corrupted playback difference seem to be happening in these cases: if HW-accelerated h264 decoding is used then I get artifacts, if software decoding is used I get frozen frame (which is normally more appropriate than showing random bits turned into video pictures).

**Comment by Pablo76** [comment]
Basically, with all time that I spent debugging the issue I can confirm that mp4box generates proper segment when seeking, and I feed these new segments to video tag; however, on chrome side it looks like it's dropping the first i-frame. I also tried to seek to 156sec - 0.5 sec to ensure that i-frame happens almost right away, but it still doesn't work well. I'm even thinking if I can build chrome (or whatever that does MSE) and debug c++ to see what bits are passed to actual decoder (is that easy to do? I mean to get a debug-able build of chrome/chromium?)

**Comment by cconcolato** [comment]
Thanks for the report. Indeed I think Chrome has a problem with the flags in the trun. I've filed a [bug there](https://code.google.com/p/chromium/issues/detail?id=518854).

**Comment by Pablo76** [comment]
I added a comment on that commit, I don't understand where and how u got these flags that you added in that commit.

**Comment by cconcolato** [comment]
Issue is too old and not sure it is still relevant.
