### ISSUE TITLE
empty stss prevents seeking

### ISSUE THREAD

**Issue by Pablo76** [gpac/mp4box.js#65]
Looks like videos edited with window movie maker have 0 entries in stss box for audio track. This prevents seeking (because audio seek results in time pos=0) and always skips to the beginning of the movie.
All other players have no issues seeking in that movie that was created with window movie maker.

**Comment by cconcolato** [comment]
Such file is not compliant. Empty 'stss' means no sync point. It's different from the absence of 'stss'. Can you share such file, I'll see what I can do? (here is an anonymous drop box if you need, please mention mp4box.js and the issue number in the description: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95)

**Comment by cconcolato** [comment]
Can you upload a file ? Otherwise I'll close the issue, you can always reopen it.
