### ISSUE TITLE
bug in wirintg full boxes that do not have their own write method

### ISSUE THREAD

**Issue by Pablo76** [gpac/mp4box.js#70]
369644ce48f6083bc1a7965754d6eb30f9b30558 introduces a bug for fullBoxes that do not have their own .write method.
parseDataAndRewind always reads version+flags, and then on write method they will be written second time.
If you diff outputs from this version and previous one you'll notice that some of the boxes got 4 extra bytes

**Comment by Pablo76** [comment]
and proposed fix:
	if (box.write === BoxParser.Box.prototype.write) {
		Log.warn("BoxParser", type+" box writing not yet implemented, keeping unparsed data in memory for later write");
		box.parseDataAndRewind(stream);
		// BEGIN FIX
		box.writeHeader = BoxParser.Box.prototype.writeHeader;
		// END OF FIX
	}

**Comment by cconcolato** [comment]
Thanks for the report and the proposed fix. I'll look at it asap. Do you have an example of FullBox that does not have a write method at the moment?

**Comment by Pablo76** [comment]
meta
another point: `meta` might be full and regular header.

**Comment by Pablo76** [comment]
FYI, I came to conclusion that DataStream.prototype.writeUint8Array is broken

**Comment by Pablo76** [comment]
Another place that got broken by the commit: BoxParser.sgpdBox.prototype.parse. Check that place that used to have !BoxParser.parseForWrite inside if: now it takes different code path when parsing for writing and results in an error eventually.

**Comment by cconcolato** [comment]
I could reproduce the bug regarding the double writing of the version+flags field. I've fixed it (I think!)

> provided that other issues all over the place are also fixed.

I think I fixed it for all the other types (Box, FullBox, SampleEntry, SampleGroup, ItemReference and TrackReference). The idea is to check if a write method is available and if not, do a shallow parsing (in this.data), then rewind and then deeply parse.

> I came to conclusion that DataStream.prototype.writeUint8Array is broken

Can you provide an example? Replacing DataStream by another library is on the roadmap but haven't had time to look for others. Any idea?

I'm closing the issue. If you find a problem, reopen or file a new issue.
