### ISSUE TITLE
vmhd.flags is 0 even if original source had 1

### ISSUE THREAD

**Issue by Pablo76** [gpac/mp4box.js#71]
dc84e42dc955677c86f83e6fa9d2f9f77c02472d always sets flags to 0 in vmhd, however, [according to apple](https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-25642) it should always be set to 1:
    A 3-byte space for video media information flags. There is one defined flag.
    No lean ahead
        This is a compatibility flag that allows QuickTime to distinguish between movies created with QuickTime 1.0 and newer movies. You should always set this flag to 1, unless you are creating a movie intended for playback using version 1.0 of QuickTime. This flag’s value is 0x0001.

**Comment by cconcolato** [comment]
Thanks for the information. I had never seen that part of the QuickTime spec. The ISOBMFF is clear that the flag should be 0. I'll raise an issue at MPEG to fix the spec. In the meantime I'll probably leave the flags untouched. Do you have an example of file with the flag set to 1?

**Comment by cconcolato** [comment]
My mistake. I read 'mvhd' instead of 'vmhd' ! Indeed ISOBMFF says that 'vmhd' should have flags set to 1, always!
