### ISSUE TITLE
Request: list keyframe byte offsets from header metadata

### ISSUE THREAD

**Issue by her34** [gpac/mp4box.js#73]
Can mp4box.js parse and list the keyframe byte offsets of single large non-fragmented mp4 files?

This would allow it so that user can download just few kb of mp4 to parse header then use byte offsets to play file using Media Source Extension.

**Comment by cconcolato** [comment]
Yes that's possible. The method for that is [mp4box.getTrackSamplesInfo](https://github.com/gpac/mp4box.js/blob/master/src/mp4box.js#L599). You can check its use in the [online file analyzer](http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html). Choose a file, go to sample view, choose a track and you'll see all samples with their properties (RAP, size, offset ...).
