### ISSUE TITLE
Memory hog

### ISSUE THREAD

**Issue by mafrost** [gpac/mp4box.js#74]
When using this lib within a streaming context, when a service just keeps on going, it just uses more and more memory until it crashes because all memory is used. This happens even if you do releaseUsedSamples.

**Comment by cconcolato** [comment]
The MP4Box constructor has a boolean to enable discarding mdat data. By default, the data is kept. Can you check if it works with it set to false.

**Comment by cconcolato** [comment]
I'm closing, reopen if you think the issue still exists.

**Comment by diegocr** [comment]
Hi there,  i was going to file an issue for the same matter.

I did tried to set the constructor boolean to _false_, so that the mdat data is discarded, but doing so the video is no longer playable. Perhaps the data is discarded too soon, any idea?
