### ISSUE TITLE
 Files have non-proportional track layouts (720x480 vs 640x360) error

### ISSUE THREAD

**Issue by HimanshuN** [gpac/mp4box.js#80]
Can anyone please help me in understanding this "File have non-proportional track layouts(720 * 480 vs 640 * 360)" ? I am not able to get the problem. It is coming when I am trying to create a single mpd file for 2 videos. The command I am using is "MP4Box -dash 2000 -rap -frag-rap -profile onDemand -out mpd v480.mp4#video v360.mp4#video v480.mp4#audio"  which is generating a wrong mpd which is not running complete videos

**Comment by rbouqueau** [comment]
Not related to mp4box.js. Closing.
