### ISSUE TITLE
publish latest release to npm repository

### ISSUE THREAD

**Issue by philikon** [gpac/mp4box.js#81]
Thanks for an incredibly useful library! Would it be possible for you to continue to publish the latest releases to the npm repository at http://npmjs.com? It would make installing them in an npm-based environment much easier. Thanks!

**Comment by cconcolato** [comment]
Thank you. I thought I had setup Travis to auto publish to npm. I'll have to check. I've just pushed a new version manually. 

I'm curious to know how you use MP4Box.js Let met know.

Also if there's other improvement I can do by filing new issues.

**Comment by cconcolato** [comment]
I've fixed Travis settings to auto-deploy to npm. I'm closing this issue. File a new issue if this is not working.

**Comment by philikon** [comment]
Thanks much!
