### ISSUE TITLE
missing documentation and file.mp4 not working

### ISSUE THREAD

**Issue by JenGL** [gpac/mp4box.js#84]
what exactly returns the method appendBuffer(data) ? in the demo it seems to return the total size of the buffers appended to mp4box, but when I try to append an ArrayBuffer of 262128 bytes it return another number... (much more bigger)

Anyway the mentioned file doesn't trigger the onReady callback even if I append the entirre file.
lnk to the file: https://we.tl/I9s1wNPUQA

**Comment by cconcolato** [comment]
The function `appendBuffer` is documented here:
https://github.com/gpac/mp4box.js#appendbufferdata

Your file works fine in the demo player and analyzer, even if I use a chunk size larger than the file. Your problem most likely comes from your appending sequence and the fact that your file has the `moov` box at the end. Can you check?

**Comment by JenGL** [comment]
Sorry. I didn't saw the return statement.

> Returns the offset (in the original file) that is expected to be the fileStart value of the next buffer. 

but as I said it's normal that if I append a chunk of 262128 byte the appendBuffer() returns 3034782

` function dl() {
              streamer.getNext().then(function(chunk) {
                chunk.fileStart = bytePointer; // bytePointer initialized to 0
                console.log(chunk.byteLength) // prints 262128
                bytePointer = mp4box.appendBuffer(chunk);
                console.log(bytePointer) // prints 3034782
                if (streamer.others()) {
                  dl();
                }
              });
            };
            dl();`

**Comment by cconcolato** [comment]
Yes it is normal. Your file has a box order which is not optimize for linear parsing. It has the `moov` box at that position at the end of the file. MP4Box.js needs to parse that box first, before being able to do anything else.

**Comment by JenGL** [comment]
so the nex't chunk has to be appended at the position 262128 or at the 
position returned by the appendbuffer method  ?


Il 12/04/2016 15:55, Cyril Concolato ha scritto:

**Comment by cconcolato** [comment]
Until you provide a buffer containing the moov box, appendBuffer will keep returning the same value and will cache the buffers internally. I would suggest providing next the buffer as suggested by the return value or providing a single buffer containing the whole file. Do you still have the problem when you feed the entire file in 1 buffer ?

**Comment by cconcolato** [comment]
Are you still having a problem or can we close the issue?
