### ISSUE TITLE
Video freezed after seek

### ISSUE THREAD

**Issue by KingSora** [gpac/mp4box.js#88]
Hello!

There is a issue with seeking of a Video.
Situation:
You have a Video with a total duration of 20 seconds. After 10 seconds of watching you decide to seek the Video to 3 seconds. Now you will see that the video (image) is freezed but the sound is continuing. If your video has reached 5 seconds the video image is continuing simultaneously with the sound, and the video is continuing without problems. There was 2 seconds where just the sound was running and the screen was freezed. If you watch again until 10 seconds and seek back to the 5 seconds where your video-image and the sound continued playing simultaneously, the seeking doesnt have any problems.

It seems like there are some sort of "checkpoints" where the video and the sound continues simultaneously and if you dont seek to one of these "checkpoints" the video-image will be freezed until you reach someone.

This bug exists also on the demo page.

Best regards!

**Comment by rbouqueau** [comment]
Hi,

Thanks for reporting. What's your browser? I cannot reproduce with Chrome 50 in Windows + demo page (counter unfragmented).

**Comment by KingSora** [comment]
Windows 7, Chrome Version 50.0.2661.102 m 

https://www.youtube.com/watch?v=sfnXdFy3xSs&feature=youtu.be

Here you can see, the video stuck for about 2 seconds, but the sound continues. Unfortunetly I cant record my system sound.

**Comment by rbouqueau** [comment]
I can see, thank you. How can we reproduce i.e. what's the URL of your video?

**Comment by KingSora** [comment]
Select or set URL:
Video with 3D graphical overlays  ||   URL: ./mp4/helloTeaser.mp4

**Comment by rbouqueau** [comment]
Thanks. I have a hi-dpi screen here and I can't access the seek-bar on this content (the 3D parts is oversized and the bar is probably displayed below the video zone). It works with other contents (such as the 2D one). Is your issue related to this content only?

Let's see if someone else can have the same behaviour as yours.

**Comment by KingSora** [comment]
The 2D one is affected with this bug too. The same bug occurs on Ubuntu 16 with chrome 50

**Comment by cconcolato** [comment]
Hi,

Thank you for your interest in mp4box.js. I don't think the problem you're encountering is an mp4box.js's bug. It's more a complex issue related to how browsers seek, with this content. 

Upon seeking, the demo player checks if the seek point is already in the browser's buffer. If it is, it simply tells the browser to seek. If it is not, mp4boxjs feeds the browser with the missing data around the seek point. That's it. The seeking and in particular video freezing or audio/video sync is handled natively by the browser. For the content you are referring to 'helloTeaser.mp4', it has random access points at times 0, 3s, 4.24s, 7.24s, 10.24s, 13.24s and 16.24s in the video stream. So if you seek outside of these points, you'll hit the problem that the video decoder has to wait for the next random access point to start playing the video. HTH.
