### ISSUE TITLE
Demux the mp4 Container

### ISSUE THREAD

**Issue by sassyn** [gpac/mp4box.js#90]
Hi,

I'm looking for a way to get the raw data from a mp4 container, so I could extract the h264 video data and the AAC audio data (either in nodejs or in the user browser)

The mp4 is a ISO Media, MP4 Base Media v1 with the following Metadata

ffprobe videofull.mp4 

> ```
> major_brand     : isom
> minor_version   : 512
> compatible_brands: isomiso2avc1iso6mp41
> title           : bg2bj01low
> encoder         : Lavf57.25.100
> Duration: 00:00:09.17, start: 0.000000, bitrate: 1062 kb/s
> Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 937 kb/s, 29.85 fps, 30 tbr, 15360 tbn, 60 tbc (default)
> Metadata:
>   handler_name    : VideoHandler
> Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
> Metadata:
>   handler_name    : SoundHandler
> ```

I can extract the raw data using FFMPEG like this:

For Video
`ffmpeg  -y -i videofull.mp4  -profile:v baseline -level 3.0 -vcodec libx264  -preset fast -b:v 500k -maxrate 500k -bufsize 1000k -r 25 -qmin 2 -qmax 22 -f h264 - > video.h264`

> file video.h264
> video.h264:JVT NAL sequence, H.264 video, baseline @ L 30

For Audio
`ffmpeg  -y -i videofull.mp4   -vn -c:a libfdk_aac -b:a 128k -flags low_delay -f adts -strict -2 -> audio.aac`

> file audio.aac
> audio.aac: MPEG ADTS, AAC, v4 LC, 44.1 kHz, stereo

I want to do the same using mp4box.js without the use of ffmpeg, but not sure if this can be done?
If so, maybe someone can provide quick example?

Thank You!

**Comment by cconcolato** [comment]
MP4Box.js is capable of extracting the sample data. I've just added a NodeJS example for that: https://github.com/gpac/mp4box.js/blob/master/test/node/extract.js
Now, for each codec you have to check if the sample data has to be modified before being written to file (e.g. for H.264) or not.

**Comment by sassyn** [comment]
Thank you @cconcolato ! You are a magician!
I really appropriate your quick response. 

I'm a new baby when it come to writing code and understand binary formats, so your example is really helpful.

However, I used the example but the output doesn't seems to be working as expected:

For example:

`./node extract.js orig.vid.mp4 1 `

give me the following file:
track_1.raw

As well as 

`./node extract.js orig.vid.mp4 2 `

track_2.raw

Both files do contains the raw data, but none of them are seems to be playable with VLC or ffmpeg.

If I take a look in the raw data of the video.h264 file that was produces using FFMPEG - I can see  tit has the ISO 14496-10 Annex B "0x000001" prefix on the NAL units.
I used the xxd -p video.h264 > video.h264.txt for this, here is small cut and paste:

**f000000001**419a3817e4ec4abe18e088daba
6889224e7f9fcfe7ff821e615c23ef61fb135b84394b8ae2fa0916faf574
5443c08dc48f15c5f178bae58adf37438768aea3aa1ee8a992ea64be8834
697aa3c7aa3b13c8132b13b104bc93b1c27d0407697a1187d0b06c913d47
6843984eae11e84193ea549f98ef589e2cf15f15e11e828d3f0482ef73d1
309430577e6f808bc4987f8eeefbbcaeb9aafb55711dddf7d18754fd08a9
fa167aba142355d7f6f54134633f2d5e41619d0a4753f420be27aa032335
08f5fcbd5feaf5d7a4eaf2747327d441d0f27d0a3bdeef88e2377bef2f96
af94b7b89e860f23b3f0523d4562fd5ddf17d5d44669ba1876593a1229a2
38a28bd1c562a7abb32ae23a1823d27386d7f86aff823a0a23a0572097ac
813627afd6bf3e62122069a529b27414cc02b450806e7ccf99732e173975
c45f439346f420748f25eacaeb093751e515ca2f77f29c5715fd0e1da279
4bb8aced227ad4bf985bae4e84112ba9c515c59d5f57fc5d5dd55deb9865
6592ea3d422a4d0b1917938080cbd9f15c9c110817bce911d107949d5321
5d5320d74548bd11225d53279440b9699685a616e2c9bbeeef97aa9ba210
17d440d4b511edea6ec26175d1f13c10850fdf1d2fa2a3b137461e17d147
6bea3eae883ca6e2c4bbeef8a820c33d47153e5a8**000000001**419a402fc0
8fecf7a873d0ea829f5720bfd7f0ffa3a3a83af304c57c097e614b782bf1
1d57555e6bae11f37751fe8734579422ef84fd041a09ad7f043e508d6a10
f0977777c1a792b79026cfd7eb5f8242ff75c1ef988ef93d083a57a90515
e2ceebbaff17755775581b3c5f55d541bf8baaeab82c8000000001419a60
2fc08fecf5b873d0ee829f5620bfd6d0ffa2a3b037fb1ef8ac2de623d60a

Doing the same of the track_1.raw (xxd) I can't see the NAL units.

What do u recommend me to do?

Is there any IRC channel for this? or other method to contact you online?

Thanks allot!

Sassy

**Comment by cconcolato** [comment]
Unfortunately, extracting raw sample data is only the first 'simple' part. The second part is fiddling with that data to store it in a useful way for players, ie. in a standard way. What's problematic is that this fiddling is media specific: different for H.264, for AAC ... I've started coding some methods for HEVC (not yet pushed) migrating the code from MP4Box (not JS). I imagine you could do that as well for the formats you want. BTW, if you don't need to do it in the browser, why not use MP4Box.exe (not MP4Box.js) directly?

**Comment by cconcolato** [comment]
Can we close this issue or do you have any specific problem?
