### ISSUE TITLE
SHVC playout

### ISSUE THREAD

**Issue by arianaa30** [gpac/mp4box.js#93]
I've noticed MP4box is able to play SHVC (Sclaable HEVC) streams which are produced by SHM. Is that right?
I'm targeting Android. I was wondering if we can use that to play SHVC streams on Android as well?

**Comment by cconcolato** [comment]
Your confusing MP4Box, MP4Client and MP4Box.js.
  - MP4Box does not play anything
  - MP4Client plays SHVC on Desktop
  - MP4Box.js per se does not play anything. It can be used with native browser supports to play some files, but currently browsers don't support SHVC. Unless you want to compile an SHVC decoder to Javascript, MP4Box.js can't do much.

**Comment by arianaa30** [comment]
Yes, I'm new to this and my information is limited. So apparently MP4Client is the only option we should look into. Is it within realms of possibilities to port the desktop decoder to Android, with less efforts?
