### ISSUE TITLE
impossible to decode appended buffer in firefox/safari

### ISSUE THREAD

**Issue by publicocean0** [gpac/mp4box.js#94]
I developed a new player class , a parser  wrapper  for mp4 type (in future i will develop a parser also for webm) and a streamer class.

I tested my player with a file downloaded by your page.It is working in chrome (v.51). 

There are 2 problems essentially: 
1. using firefox 49 your page is not working (impossible to decode segments) . I tested that file:///home/cristian/Video/Anand-Carlsen2014.mp4  is working if i read it directly so it is not a problem with codecs. 
2. I tried to download other mp4 files from other sites like https://media.w3.org/2010/05/sintel/trailer.mp4
   the info are parsed correctly but then no segment is detected. Pratically a lot of other file downloaded from other sites has same problem.

**Comment by cconcolato** [comment]
Thanks for the report. 

Regarding Firefox, I have indeed the same problem with version 50.0a1. I'll try to investigate.

Regarding the sintel file, as you can see if you load it in the [file analyser](http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html) that file is not segmented (no moof box). There are plenty of MP4 files out there that are not segmented. That's exactly what MP4Box.js is designed for: to do on-the-fly segmentation. You have to pass the buffer to MP4Box.js and request segmentation. (See [README.md](https://github.com/gpac/mp4box.js/blob/master/README.md))

**Comment by publicocean0** [comment]
sorry maybe i explained badly second point. I did it as you told above. For this reason i reported it.  Passing trailar.mp4 to Mp4box requesting segmentation no segment is detected: call back onready is called correctly but then no other callback is executed.

**Comment by publicocean0** [comment]
just moment  i try  again with analizer... uhmmm

**Comment by publicocean0** [comment]
i debug analizer page. 
I saw : 
- onsegment is null. 
- use mp4box.inputIsoFile. 
I tried to patched your analizer page adding 

 <pre>
mp4box.onReady=function(info){
		
	return;	
	};
</pre>
Comparing the behaviour of mp4box in my player and in analizer  
it is identical until on ready callback. 
They have 2 tracks correctly. Then in my player 2 tracks are set for showing segments but then no segment are show. 
I have a doubt. This file has hasMoov= true. Maybe in this case no segment is produced?

**Comment by cconcolato** [comment]
You misunderstood me:
  - The file analyzer does not perform any segmentation. It only shows the content of the initial file. The BigBuckBunny is like Sintel, they are not initially segmented (no moof). 
  - The player application does perform segmentation, to feed MSE buffers. When I try with both files (BigBuckBunny and Sintel trailer), both play fine (ie. the segmentation works fine). 

Does it work for you in the demo player? 
I suspect it is a bug in the integration of MP4Box.js in your application? Can you share the code or can you post a log of the calls to MP4Box.js you are making?

**Comment by publicocean0** [comment]
Ah very strange. I will investigate ....

My player received in input a class streamer. A class streamer can stream a general inputstream. In the demo im working with FileStreamer. 
Inside the player there is a factory so it make a instance of the parser for the format file. For now i have just mp4 parser. 
I have to complete part for bandwith ... but i can see a video with files downloaded in your page.
It is my initial version :)

[aa.ftl.zip](https://github.com/gpac/mp4box.js/files/335598/aa.ftl.zip)

**Comment by publicocean0** [comment]
solved problem point 2) 
it seams i solved also endOfStream callback. 

It remains point 1)  
in my firefox the error is 

<pre>
StreamPlayer:Source openedaa:1393:22
FileStream:ready to read file trailer.mp4 , size = 4372373aa:1393:22
FileStream:read offset [0,65535] , packet bps 524288000, bandwidth 524288000aa:1393:22
FileStream:set offset 4332917aa:1393:22
FileStream:read offset [4332917,4358996] , packet bps 52160000, bandwidth 288224000aa:1393:22
StreamPlayer:starting to parse movie informationaa:1393:22
FileStream:read offset [4358997,4372372] , packet bps Infinity, bandwidth Infinityaa:1393:22
FileStream:done reading file +4372373aa:1393:22
StreamPlayer:adding sourceBuffer #1 for type 'video/mp4; codecs="avc1.64001e"'aa:1393:22
StreamPlayer:sourceBuffer #1 - appending initial bufferaa:1393:22
StreamPlayer:adding sourceBuffer #2 for type 'video/mp4; codecs="mp4a.40.2"'aa:1393:22
StreamPlayer:sourceBuffer #2 - appending initial bufferaa:1393:22
FileStream:set offset 65536aa:1393:22
StreamPlayer:ready to segmentation ...aa:1393:22
GET 
http://127.0.0.1:8080/streamer/test/aa [HTTP/1.1 200  10ms]
FileStream:read offset [65536,131071] , packet bps 74898285.71428572, bandwidth Infinityaa:1393:22
MP4Parser:received new segment for track 2 up to sample #100aa:1393:22
StreamPlayer:sourcebuffer#2 - adding segment 1, pending count: 1aa:1393:22
StreamPlayer:sourceBuffer #2 - appending new buffer, pending: 0aa:1393:22
StreamPlayer:sourceBuffer #2 - error aa:1393:22
StreamPlayer:sourcebuffer # 2 - update endedaa:1393:22
Impossibile decodificare la risorsa multimediale mediasource:http://127.0.0.1:8080/dc0d614d-331f-4d4b-88d3-6218e3b4dd19.aa
StreamPlayer:source closed, error: "general"aa:1393:22
FileStream:read offset [131072,196607] , packet bps 37449142.85714286

        
</pre>

pratically impossible to decode the resource after

**Comment by publicocean0** [comment]
i tested also safari supporting MSE and mp4. A problem decoding mp4 also in safari. :(

**Comment by publicocean0** [comment]
i discovered in firefox is not triggered event 'loadedmetadata'. Probably the bug  'Impossibile decodificare la risorsa multimediale mediasource:http://127.0.0.1:8080/dc0d614d-331f-4d4b-88d3-6218e3b4dd19.aa' could be binded with initial metadata.

**Comment by cconcolato** [comment]
For the record, Firefox bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1283984

**Comment by publicocean0** [comment]
I saw firefox notified a bug. Consider that same problem is also using safari.

**Comment by publicocean0** [comment]
Consider that every movie tried dont works so ftyp is missing in every starting segment.

**Comment by publicocean0** [comment]
cool in firefox it works now :)

**Comment by publicocean0** [comment]
i will test also in safari asap

**Comment by publicocean0** [comment]
it works also in safari (where mse is supported obviously (not ipad))

**Comment by publicocean0** [comment]
good work:)
