### ISSUE TITLE
appendBuffer api improvement

### ISSUE THREAD

**Issue by publicocean0** [gpac/mp4box.js#95]
now it is impossible to understand when a stream is ended.

if you change signature  appendBuffer(buffer) into appendBuffer(buffer,last=false) that is compatible with previous versions , you can notify if a segment is the last segment and so you can call mediasource.endOfStream and so video event 'ended' can be executed.

**Comment by cconcolato** [comment]
Currently, MP4Box.js does not have any link to a MediaSource/SourceBuffer object. The intent is rather that the application integrates MP4Box and MediaSource, and a download object (XHR, ...). If the download object knows it has received the last buffer, it should pass it to MP4Box as usual and call `flush` to make sure all remaining samples are flushed in the generated segments. What's missing indeed is an indication in the `onSegment` callback that the last segment was sent. Would that solve your problem if a boolean was adeed: `onSegment(id, user, buffer, is_last)`?

**Comment by publicocean0** [comment]
yes , i developped on my own a player ... but onended event is not thrown because mediasource is never closed. My appender has last info so i know when i pass last block (not segmented) but then i miss this info because i receive just segments . 1 raw block could contains also multiple segments so is not foreseable. Surely onSegment(id, user, buffer, is_last) could solve this.

**Comment by publicocean0** [comment]
i solved also the end of stream.I tested with 3 movies ... it works. I hope no bugs :) Really is not so simple as i imagined. It is necessary to understanding pending source buffers, how many updates to do , the window when is started /finished last file buffer

**Comment by cconcolato** [comment]
Glad you solved your problem. Closing the issue. Reopen if needed.
