### ISSUE TITLE
question about progressive streaming/segments offfset

### ISSUE THREAD

**Issue by publicocean0** [gpac/mp4box.js#97]
hi , i have a question. 
***ipothesis: 
1) i have a progressive stream mp4 so header is on the first byte blocks.
2) i can't seek in the stream  

***question 
Could be possible, using your library, to see a video in those condictions? I m thinking in particular way about the api appendBuffer that returns a offset. If i dont consider this offset and i continue to append buffers in progressive way what does it happen?
I m thinking in particular way to live stream where it is not possible to seek because stream arrives on the fly. 

---

***ipothesis: 
1) i have a dash file giving me infos about segments offsets
2) i supposing you scan all the file for saving in a array all the offsets of the segments

**\* question: 
considering i have a dash file telling me the segments/position without to scan all the file. 
It is difficult to add directly the segments info directly in mp4box permitting to skip the file scanning of segments?

**Comment by cconcolato** [comment]
> If i dont consider this offset and i continue to append buffers in progressive way what does it happen?

Nothing until you actually reach the offset. You should be fine with a continuously arriving stream.

> It is difficult to add directly the segments info directly in mp4box permitting to skip the file scanning of segments?

I don't understand what you mean by "adding the segments info" or "skip the file scanning". If you have the segment boundaries from a DASH manifest, simply append the segments with MSE, without MP4Box.js.

**Comment by publicocean0** [comment]
when i seek time X , mp4box converts it into  a file offset. I think this offset is the start of the nearest segment. 
For knowing the nearest segment i imagine you have a map map(time->offset).   For having this map you scanned all the file before to start the segmentation events. 
For calculating the next segment i could to do:

time =size*8 /bandwidth. 

So i might have the size info for foreseeing exactly how much time i need for downloading in time it. 
The ways for having that size in advance for me are 2: 
-1) having a additional info as in dash files (this info are precalculated before)
-2) notifying the size of next segment before it starts to download. It takes the advantage considering  normally a protocoll write on the top   'segment size' of the same. Using a temporal window i would foresee if the future the velocity/time of download needs to encrease or to reduce. 
i m evaluating what to do considering also the logic of mp4box.

**Comment by cconcolato** [comment]
Yes, MP4Box.js maintains a map (time, offset) for each frame (not each segment). But it does not read the entire file for that. If the file is not fragmented, the entire information is in the moov box. If it is fragmented, then there is no information about the frames not yet received. 

I'm not sure I follow you. When using MP4Box.js, it is MP4Box that produces the segments, they are not downloaded. If you have segments to download, why do you want to use MP4Box.js ? Download them directlty and feed them to MSE. Or do you want to know how much data MP4Box.js needs to produce the next segment ?

**Comment by publicocean0** [comment]
yes  I want to know how much data MP4Box.js needs to produce the next segment .
My player is abstract so it dont know about mp4. It uses a interface Stream class.  Mp4Stream is a class extending a Stream. The same thing i m developping with webm ( a kind of WebmBox :) ). So player can work with any stream type. Can i retrieve/calculate the size of a segment using infos inside mp4box(not using onsegment)?
