### ISSUE TITLE
How to make segments of 1 second long each like in native MP4Box -frag 1000?

### ISSUE THREAD

**Issue by CodeTrol** [gpac/mp4box.js#98]
In segmentation example you use nbSamples to set a size of segment:

``` js
mp4box.setSegmentOptions(info.tracks[i].id, null, { nbSamples: 1000});
```

what would be equivalent to native's command?

```
MP4Box -dash 1000 -frag 1000 <file>
```

I tried `info.tracks[i].timescale/1000` as nbSamples but it does not give the same result as native.
Also I tried to modify the code based on `mp4box.seek` method. I've made `sample` exposed in `createFragment` method:

``` js
return {
        stream: stream,
        sample: sample
    };
```

and updated `processSamples` as well:

``` js
var fragment = this.createFragment(this.inputIsoFile, fragTrak.id, trak.nextSample, fragTrak.segmentStream);
var result = fragment && fragment.stream;
```

and replaced the code below:

``` js
var canSegment = false;
    if(fragTrak.nb_samples != null)
        canSegment = trak.nextSample % fragTrak.nb_samples === 0;
    if(fragTrak.segmentTime != null)
    {
        if(fragment.sample.cts > fragTrak.sTime * fragment.sample.timescale){
            fragTrak.sTime += fragTrak.segmentTime;
            canSegment = true;
            console.log('got time fragment', fragment.sample.cts, fragTrak.sTime, fragment.sample.timescale); // debug
        }
    }
    if (canSegment || trak.nextSample >= trak.samples.length) {
/* code */
```

For this code I used `{nbSamples:1/0,segmentTime:1}` in `setSegmentOptions` but I missed something if it still does not work.

Thanks forward for any reply!

Note: `sTime` is a "counter" and it's defined in `setSegmentOptions` as follows:

``` js
if (options.segmentTime) {
    fragTrack.sTime = fragTrack.segmentTime = options.segmentTime;
}
```

**Comment by cconcolato** [comment]
Issue is too old. If you still have the problem, please open a new issue.
